### ISSUE TITLE
Sum Of Cubes

### ISSUE THREAD

**Issue by Master-Helix** [SarthakKeshari/CPP-Questions-and-Solutions#103]
### Enter your question - 

You are given a positive integer x. Check whether the number x is representable as the sum of the cubes of two positive integers.

Formally, you need to check if there are two integers a and b (1≤a,b) such that a^3+b^3=x.

For example, if x=35, then the numbers a=2 and b=3 are suitable (2^3+3^3=8+27=35). If x=4, then no pair of numbers a and b are suitable.

**Input**
The first line contains one integer t (1≤t≤100) — the number of test cases. Then t test cases follow.

Each test case contains one integer x (1≤x≤1012).

Please note, that the input for some test cases won't fit into 32-bit integer type, so you should use at least 64-bit integer type in your programming language.

**Output**
For each test case, output on a separate line:

"YES" if x is representable as the sum of the cubes of two positive integers.
"NO" otherwise.
You can output "YES" and "NO" in any case (for example, the strings yEs, yes, Yes, and YES will be recognized as positive).

**Comment by Master-Helix** [comment]
@SarthakKeshari Sir,
Please assign me this question for  Hacktoberfest.
Thank You.

**Comment by SarthakKeshari** [comment]
@Master-Helix,
Kindly add your solution to "CodeForces" folder
Deadline - 03/10/2021
