### ISSUE TITLE
Spirally Traversing A Matrix [2D Array]

### ISSUE THREAD

**Issue by apimpulse** [SarthakKeshari/CPP-Questions-and-Solutions#105]
### Enter your question - 

Given a matrix of size r*c. Traverse the matrix in spiral form.

Example 1:

Input:
r = 4, c = 4
matrix[][] = {{1, 2, 3, 4},
{5, 6, 7, 8},
{9, 10, 11, 12},
{13, 14, 15,16}}
Output:
1 2 3 4 8 12 16 15 14 13 9 5 6 7 11 10

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/spiral-matrix/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Matrix

**Comment by apimpulse** [comment]
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
@apimpulse,
Kindly add your solution to "leetcode" folder.
Deadline - 03/10/2021
