### ISSUE TITLE
Create ATM.cpp

### ISSUE THREAD

**Issue by sej28** [SarthakKeshari/CPP-Questions-and-Solutions#107]
### Enter your question - 
Pooja would like to withdraw X $US from an ATM. The cash machine will only accept the transaction if X is a multiple of 5, and Pooja's account balance has enough cash to perform the withdrawal transaction (including bank charges). For each successful withdrawal the bank charges 0.50 $US. Calculate Pooja's account balance after an attempted transaction.

### Enter link to the question(if question belongs to any online platform) - 
https://www.codechef.com/problems/HS08TEST

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Basic

**Comment by sej28** [comment]
Hey, I would like to work on this issue!!PLease assign it to me

**Comment by SarthakKeshari** [comment]
@sej28,
Kindly add your solution to "codechef" folder.
Deadline - 02/10/2021

This Issue will only be counted towards ranking criteria of this repository.

Gentle advice -
Medium and hard level questions will be given preference for Hacktoberfest tag.
