### ISSUE TITLE
Solution-Positive Negative

### ISSUE THREAD

**Issue by Kunal22-ai** [SarthakKeshari/CPP-Questions-and-Solutions#11]
### Enter Issue id being referred to - 
#10 
### Approach/Algorithm/Pseudo Code for the selected question - 
I will use if-else to solve the issue

### Tags for the solution(eg - Array, Basic, Stack, etc.) - 
Basic(If-else)

**Comment by SarthakKeshari** [comment]
@Kunal22-ai,
Kindly place this solution in Basic Codes folder
Deadline 27/09/2021
