### ISSUE TITLE
Infix to Postfix and Infix to Prefix in cpp

### ISSUE THREAD

**Issue by Atharvp18** [SarthakKeshari/CPP-Questions-and-Solutions#110]
### A brief about your proposal - 
I would like to contribute my code for infix to postfix & prefix conversion using stack in cpp. Please assign me this task.

Thank you

**Comment by SarthakKeshari** [comment]
@Atharvp18,
Kindly follow the issue template

**Comment by Jibendu007** [comment]
@SarthakKeshari can i be assigned to this?

**Comment by SarthakKeshari** [comment]
@Jibendu007, 
Create "Add a question" issue for the above then I can assign it.
