### ISSUE TITLE
Stack Using Linked List

### ISSUE THREAD

**Issue by mack611** [SarthakKeshari/CPP-Questions-and-Solutions#115]
### Enter your question - 
Create a stack using linked list.

### Enter link to the question(if question belongs to any online platform) - 
No

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
linked list , stack , functions

**Comment by mack611** [comment]
@SarthakKeshari  pls assign me this

**Comment by SarthakKeshari** [comment]
@mack611,
Kindly add your solution to "Data Structure/Linked List/Single Linked List" folder
Deadline - 03/10/2021

**Comment by Prajakta102** [comment]
Kindly assign this issue to me

**Comment by ayushjindal23** [comment]
@SarthakKeshari I would love to try this problem.

**Comment by SarthakKeshari** [comment]
@ayushjindal23,
Kindly add your solution to "Data Structure/Stack" folder
Deadline - 05/10/2021

**Comment by ayushjindal23** [comment]
@SarthakKeshari I'm not able to pull a request for this issue. It's emerging directly into the code

**Comment by SarthakKeshari** [comment]
@ayushjindal23,
Kindly share the screenshot of the errors you are facing

**Comment by shubhamjain2001** [comment]
Please assign this issue to me

**Comment by SarthakKeshari** [comment]
@shubhamjain2001,
Its great to see your interest to solve the question. But deadline ain't over yet. You may refer to CONTRIBUTING.md for getting futher details and guidelines on how to contribute to this repo.

**Comment by ayushjindal23** [comment]
@SarthakKeshari I have submitted the PR #289
