### ISSUE TITLE
Football

### ISSUE THREAD

**Issue by Fury-MadMax** [SarthakKeshari/CPP-Questions-and-Solutions#116]
### Enter your question - 
One day Vasya decided to have a look at the results of Berland 1910 Football Championship’s finals. Unfortunately he didn't find the overall score of the match; however, he got hold of a profound description of the match's process. On the whole there are n lines in that description each of which described one goal. Every goal was marked with the name of the team that had scored it. Help Vasya, learn the name of the team that won the finals. It is guaranteed that the match did not end in a tie.

**Input**
The first line contains an integer n (1 ≤ n ≤ 100) — the number of lines in the description. Then follow n lines — for each goal the names of the teams that scored it. The names are non-empty lines consisting of uppercase Latin letters whose lengths do not exceed 10 symbols. It is guaranteed that the match did not end in a tie and the description contains no more than two different teams.

**Output**
Print the name of the winning team. We remind you that in football the team that scores more goals is considered the winner.

### Enter link to the question(if question belongs to any online platform) - 
https://codeforces.com/problemset/problem/43/A

**Comment by Fury-MadMax** [comment]
Sir @SarthakKeshari,
Kindly assign this question to me for contribution under Hacktoberfest-2021.

**Comment by SarthakKeshari** [comment]
@Fury-MadMax,
Kindly add your solution to "codeforces" folder.
Deadline - 02/10/2021

This Issue will only be counted towards ranking criteria of this repository.

Gentle advice -
Medium and hard level questions will be given preference for Hacktoberfest tag.
