### ISSUE TITLE
 Merge k Sorted Lists

### ISSUE THREAD

**Issue by Ritwik009** [SarthakKeshari/CPP-Questions-and-Solutions#117]
### Enter your question - 
You are given an array of k linked-list lists, each linked-list is sorted in ascending order.

Merge all the linked lists into one sorted linked list and return it.

 

Example 1:

Input: lists = [[1,4,5],[1,3,4],[2,6]]
Output: [1,1,2,3,4,4,5,6]
Explanation: The linked lists are:
[
  1->4->5,
  1->3->4,
  2->6
]
merging them into one sorted list:
1->1->2->3->4->4->5->6
Example 2:

Input: lists = []
Output: []
Example 3:

Input: lists = [[]]
Output: []
 

Constraints:

k == lists.length
0 <= k <= 10^4
0 <= lists[i].length <= 500
-10^4 <= lists[i][j] <= 10^4
lists[i] is sorted in ascending order.
The sum of lists[i]. length won't exceed 10^4.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/merge-k-sorted-lists/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Linked List, Divide and Conquer, Heap, Merge Sort

**Comment by Ritwik009** [comment]
@SarthakKeshari Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
@Ritwik009,
Kindly add your solution to "leetcode" folder.
Deadline - 03/10/2021
