### ISSUE TITLE
Maximum Light Up

### ISSUE THREAD

**Issue by Fury-MadMax** [SarthakKeshari/CPP-Questions-and-Solutions#118]
### Enter your question - 
Chef has allocated himself a budget of P rupees to buy Diwali crackers. There are only 3 types of crackers available in the market and each type of cracker can be bought any number of times.

1. Fuljhari, where each costs a rupees
2. Anar, where each costs b rupees
3. Chakri, where each costs c rupees

The crackers have the following interesting properties:-

- A Fuljhari can be lit on its own
- To light an Anar, you will need x Fuljharis
- To light a Chakri, you will need y Fuljharis

What's the maximum total of Anars and Chakris that Chef can light up with his given budget.

### Enter link to the question(if question belongs to any online platform) - 
https://www.codechef.com/START13C/problems/DIWALI1

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Greedy, math, implementation

**Comment by Fury-MadMax** [comment]
@SarthakKeshari Sir,
Please assign me this question for Hacktoberfest 2021.
Thank You.

**Comment by SarthakKeshari** [comment]
@Fury-MadMax,
Kindly add your solution to "codechef" folder.
Deadline - 03/10/2021
