### ISSUE TITLE
Basic Data Types

### ISSUE THREAD

**Issue by Harshit-Poddar90** [SarthakKeshari/CPP-Questions-and-Solutions#123]
### Enter your question - 
Some C++ data types, their format specifiers, and their most common bit widths are as follows:

Int ("%d"): 32 Bit integer
Long ("%ld"): 64 bit integer
Char ("%c"): Character type
Float ("%f"): 32 bit real value
Double ("%lf"): 64 bit real value

### Enter link to the question(if question belongs to any online platform) - 
https://www.hackerrank.com/challenges/c-tutorial-basic-data-types/problem

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Data Types.

**Comment by Harshit-Poddar90** [comment]
kindly assign

**Comment by SarthakKeshari** [comment]
@Harshit-Poddar90,
Kindly place your solution in "hackerrank" folder.
Deadline - 02/10/2021
