### ISSUE TITLE
Operation choice

### ISSUE THREAD

**Issue by Harshit-Poddar90** [SarthakKeshari/CPP-Questions-and-Solutions#124]
### Enter your question - 
Write a menu driven program to get the kind of operation user wants to perform on the two numeric values and return the answer accordingly

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
if-else

**Comment by Harshit-Poddar90** [comment]
kindly assign

**Comment by SarthakKeshari** [comment]
@Harshit-Poddar90,
Kindly add your solution to "Basic Codes" folder.
Deadline - 02/10/2021
