### ISSUE TITLE
Climbing Stairs

### ISSUE THREAD

**Issue by Rajat-Jain29** [SarthakKeshari/CPP-Questions-and-Solutions#129]
### Enter your question - 
You are climbing a staircase. It takes n steps to reach the top.

Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?

### Enter link to the question(if question belongs to any online platform) - 
LeetCode
https://leetcode.com/problems/climbing-stairs/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Basic

**Comment by Rajat-Jain29** [comment]
@SarthakKeshari Please assign me this issue under the label of hacktoberfest.
Thank You.

**Comment by SarthakKeshari** [comment]
@Rajat-Jain29,
Kindly add your solution to "leetcode" folder.
Deadline - 02/10/2021

This Issue will only be counted towards ranking criteria of this repository.

Gentle advice for futher Issues -
Medium and hard level questions will be given preference for Hacktoberfest tag.
