### ISSUE TITLE
Chef Zomo and Zoo

### ISSUE THREAD

**Issue by ThejaswinS** [SarthakKeshari/CPP-Questions-and-Solutions#131]
### Enter your question - 
Chef zomo runs a zoo and every afternoon after lunch he comes and makes sure that none of the animals have escaped. He has a huge list of all the animals and checks each animal off as he sees it, but thinks this is really inefficient. He only cares about what animal they are, since all similar animals share a cage. So, if he has a Capuchin monkey and Squirrel monkey, Chef only wants to know that he has two monkeys. Given an integer n, and n lines describing animals, output in alphabetical order the animals Chef has in his zoo, followed by their count.

#### Input Format
The input will contain multiple test cases, up to Five. Each test case contains a line containing a single integer n (0≤n≤10^3), followed by n lines of animals with at least one word on every line. An animal name may consist of multiple lowercase or uppercase words, with the last one describing the kind of animal. Animal names may contain apostrophes, hyphens, and periods. The input is terminated when n is 0.

#### Output Format
For each test case, output the list number, followed by the animals Chef has in his zoo in lowercase and alphabetical order, with each animal followed by one space and the delimiter | and then another space and their count.

#### Sample Input 1 
6
African elephant
White tiger
Indian elephant
Siberian tiger
Tiger
Panda bear
1
Blue Russian Penguin
0
#### Sample Output 1 
List 1:
bear | 1
elephant | 2
tiger | 3
List 2:
penguin | 1

### Enter link to the question(if question belongs to any online platform) - 
https://www.codechef.com/CDSP2021/problems/SEPT203

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Strings, Basic

**Comment by ThejaswinS** [comment]
@SarthakKeshari  Kindly please assign me this issue 
#hacktoberfest21

**Comment by SarthakKeshari** [comment]
@ThejaswinS,
Kindly add your solution to "codechef" folder.
Deadline - 03/10/2021
