### ISSUE TITLE
Median in a row-wise sorted Matrix

### ISSUE THREAD

**Issue by Adityagupta1625** [SarthakKeshari/CPP-Questions-and-Solutions#134]
### Question-
Given a row wise sorted matrix of size RxC where R and C are always odd, find the median of the matrix.

### Example:

Input:
R = 3, C = 3
M = [[1, 3, 5], 
     [2, 6, 9], 
     [3, 6, 9]]

Output: 5

Explanation:
Sorting matrix elements gives us 
{1,2,3,3,5,6,6,9,9}. Hence, 5 is median. 

### Link:
https://practice.geeksforgeeks.org/problems/median-in-a-row-wise-sorted-matrix1527/1

### Tags:
<code>Matrix</code> <code>Binary Search</code>

**Comment by Adityagupta1625** [comment]
Pls assign me this issue

**Comment by SarthakKeshari** [comment]
@Adityagupta1625,
Kindly add your solution to "GeeksForGeeks" folder.
Deadline - 03/10/2021

**Comment by Adityagupta1625** [comment]
Okk Sure
