### ISSUE TITLE
Longest Increasing Path

### ISSUE THREAD

**Issue by arihantthriwe** [SarthakKeshari/CPP-Questions-and-Solutions#136]
### Enter your question - 
Given a two-dimensional integer matrix, find the length of the longest strictly increasing path. You can move up, down, left, or right.

Constraints :
n, m ≤ 500 where n and m are the number of rows and columns in matrix

Example :
Input-:
matrix = [
    [1, 3, 5],
    [0, 4, 6],
    [2, 2, 9]
]
Output-:
6
Explanation-:
The longest path is [0, 1, 3, 5, 6, 9]

### Enter link to the question(if question belongs to any online platform) - 
https://binarysearch.com/problems/Longest-Increasing-Path

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Dynamic Programming

**Comment by Jibendu007** [comment]
@arihantthriwe can i be assigned to this?

**Comment by SarthakKeshari** [comment]
@Jibendu007,
Kindly check the link it is not giving any response

**Comment by arihantthriwe** [comment]
It's working fine.

**Comment by Jibendu007** [comment]
???

**Comment by arihantthriwe** [comment]
And i posted this to get myself assigned :) @SarthakKeshari

**Comment by Jibendu007** [comment]
okay then @arihantthriwe

**Comment by arihantthriwe** [comment]
Please check @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@arihantthriwe,
Ok they might me having some server issue.

**Comment by SarthakKeshari** [comment]
@arihantthriwe,
Kindly add you solution to "Arrays/2D Arrays" folder.
Deadline - 03/10/2021
