### ISSUE TITLE
Check if two binary trees are identical or not – Iterative and Recursive

### ISSUE THREAD

**Issue by Prajakta102** [SarthakKeshari/CPP-Questions-and-Solutions#141]
### Enter your question - 
Your answer
Write an efficient algorithm to check if two binary trees are identical or not.

### Enter link to the question(if question belongs to any online platform) - 

https://www.techiedelight.com/check-if-two-binary-trees-are-identical-not-iterative-recursive/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Your answer

binary tree,Stack

**Comment by Prajakta102** [comment]
kindly assign this task to me.

**Comment by SarthakKeshari** [comment]
@Prajakta102,
Kindly create add your solution to "Data Structure/Trees/Binary Trees".
Deadline - 04/10/2021

Strict advice -
Be original in your code. In case of found plagarism in later review even after a successful merge may lead to ban.
