### ISSUE TITLE
 average

### ISSUE THREAD

**Issue by Hitesh-bonam** [SarthakKeshari/CPP-Questions-and-Solutions#147]
### Enter your question - 
write the program for calculation average of 10 marks

### Enter link to the question(if question belongs to any online platform) - 
no link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
maths , basic

**Comment by Hitesh-bonam** [comment]
kindly assign this issue.

**Comment by SarthakKeshari** [comment]
@Hitesh-bonam,
Kindly add your solution to "Basic Codes" folder.
Deadline - 02/10/2021
