### ISSUE TITLE
Solution- Reverse an Array

### ISSUE THREAD

**Issue by Siddhant231xyz** [SarthakKeshari/CPP-Questions-and-Solutions#15]
### Enter Issue id being referred to - 
#14 

### Approach/Algorithm/Pseudo Code for the selected question - 
For Loop

### Tags for the solution(eg - Array, Basic, Stack, etc.) - 
Array

**Comment by SarthakKeshari** [comment]
@Siddhant231xyz,
Kindly add this solution to Basic Codes folder
Deadline 27/09/2021.
