### ISSUE TITLE
Zipped String

### ISSUE THREAD

**Issue by arihantthriwe** [SarthakKeshari/CPP-Questions-and-Solutions#150]
### Enter your question - 
Given lowercase alphabet strings a, b, and c return whether there's any way of obtaining c by merging characters in order from a and b.

Constraints:

0 ≤ n ≤ 1,000 where n is the length of a
0 ≤ m ≤ 1,000 where m is the length of b
0 ≤ k ≤ 1,000 where k is the length of c

Example 1
Input:-
a = "abc"
b = "def"
c = "abdefc"
Output:-
true

### Enter link to the question(if question belongs to any online platform) - 
https://binarysearch.com/problems/Zipped-String

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Dynamic Programming
String

**Comment by arihantthriwe** [comment]
Pleas assign me this :) @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@arihantthriwe,
Kindly add you solution to "String Handling" folder.
Deadline - 03/10/2021
