### ISSUE TITLE
1569C - Jury Meeting || CodeForces

### ISSUE THREAD

**Issue by jainsanyam228** [SarthakKeshari/CPP-Questions-and-Solutions#151]
### Enter your question - 
n people gathered to hold a jury meeting of the upcoming competition, the i-th member of the jury came up with ai tasks, which they want to share with each other.

First, the jury decides on the order which they will follow while describing the tasks. Let that be a permutation p of numbers from 1 to n (an array of size n where each integer from 1 to n occurs exactly once).

Then the discussion goes as follows:

 

- If a jury member p1 has some tasks left to tell, then they tell one task to others. Otherwise, they are skipped.
-  If a jury member p2 has some tasks left to tell, then they tell one task to others. Otherwise, they are skipped.
- ...
-  If a jury member pn has some tasks left to tell, then they tell one task to others. Otherwise, they are skipped.
-  If there are still members with tasks left, then the process repeats from the start. Otherwise, the discussion ends.
-  A permutation p is nice if none of the jury members tell two or more of their own tasks in a row.

Count the number of nice permutations. The answer may be really large, so print it modulo 998244353.

Enter link to the question(if question belongs to any online platform) - 
[https://codeforces.com/problemset/problem/1569/C](https://codeforces.com/problemset/problem/1569/C)
 Tags for the question(eg - Array, Basic, Stack, etc.) - 
maths , combinatorics

**Comment by jainsanyam228** [comment]
@SarthakKeshari Kindly please assign me this issue
#hacktoberfest21

**Comment by jainsanyam228** [comment]
@SarthakKeshari  please assigh

**Comment by SarthakKeshari** [comment]
@jainsanyam228,
Kindly add your solution to "codeforces" folder.
Deadline - 04/10/2021
