### ISSUE TITLE
Date Validation

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/CPP-Questions-and-Solutions#152]
### Enter your question - 
Write a program to validate the date entered by the user.
Date format - dd/yyyy/mm

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
String Handling, if

**Comment by PrashantSrivastava33** [comment]
please assign me this question

**Comment by SarthakKeshari** [comment]
@PrashantSrivastava33,
Kindly add your solution to "String Handling" folder
Deadline - 03/10/2021

**Comment by PrashantSrivastava33** [comment]
Could you kindly extend my submission deadline till 12pm tomorrow? (12:00 PM 04/10/2021) @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Sure,
New(Final) deadline - 04/10/2021

**Comment by ayushjindal23** [comment]
@SarthakKeshari Can I have this problem, I have basic idea for solving it.
