### ISSUE TITLE
Permutations

### ISSUE THREAD

**Issue by smitaranii** [SarthakKeshari/CPP-Questions-and-Solutions#154]
### Enter your question - 
Given an array nums of distinct integers, return all the possible permutations. You can return the answer in any order.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/permutations/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array Backtracking
Can  you assign me this question?

**Comment by PrashantSrivastava33** [comment]
please assign me this question @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@smitaranii,
Kindly add your solution to "leetcode" folder.
Deadline - 03/10/2021
