### ISSUE TITLE
Dungeon Game

### ISSUE THREAD

**Issue by Ritwik009** [SarthakKeshari/CPP-Questions-and-Solutions#155]
### Enter your question - 
The demons had captured the princess and imprisoned her in the bottom-right corner of a dungeon. The dungeon consists of m x n rooms laid out in a 2D grid. Our valiant knight was initially positioned in the top-left room and must fight his way through the dungeon to rescue the princess.

The knight has an initial health point represented by a positive integer. If at any point his health point drops to 0 or below, he dies immediately.

Some of the rooms are guarded by demons (represented by negative integers), so the knight loses health upon entering these rooms; other rooms are either empty (represented as 0) or contain magic orbs that increase the knight's health (represented by positive integers).

To reach the princess as quickly as possible, the knight decides to move only rightward or downward in each step.

Return the knight's minimum initial health so that he can rescue the princess.

Note that any room can contain threats or power-ups, even the first room the knight enters and the bottom-right room where the princess is imprisoned.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/dungeon-game/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Dynamic Programming, Matrix

**Comment by Ritwik009** [comment]
@SarthakKeshari Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
@Ritwik009,
Kindly add your solution to "leetcode" folder
Deadline - 03/10/2021
