### ISSUE TITLE
Higher Order Functions

### ISSUE THREAD

**Issue by Hariprasad19036** [SarthakKeshari/CPP-Questions-and-Solutions#159]
### Enter your question - 
Helen studies functional programming and she is fascinated with a concept of higher order functions — functions that are taking other functions as parameters. She decides to generalize the concept of the function order and to test it on some examples.

For her study, she defines a simple grammar of types. In her grammar, a type non-terminal T is defined as one of the following grammar productions, together with order(T), defining an order of the corresponding type:

"()" is a unit type, order("()")=0.
"(" T ")" is a parenthesized type, order("("T")")=order(T).
T1 "->" T2 is a functional type, order(T1"->"T2)=max(order(T1)+1,order(T2)). The function constructor T1 "->" T2 is right-to-left associative, so the type "()->()->()" is the same as the type "()->(()->())" of a function returning a function, and it has an order of 1. While "(()->())->()" is a function that has an order-1 type "(()->())" as a parameter, and it has an order of 2.
Helen asks for your help in writing a program that computes an order of the given type.

Input
The single line of the input contains a string consisting of characters '(', ')', '-', and '>' that describes a type that is valid according to the grammar from the problem statement. The length of the line is at most 104 characters.

Output
Print a single integer — the order of the given type.

Examples
input
()
output
0
input
()->()
output
1
input
()->()->()
output
1
input
(()->())->()
output
2
input
()->(((()->())->()->())->())
output
3

### Enter link to the question(if question belongs to any online platform) - 
https://codeforces.com/contest/1578/problem/H

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Divide and conquer, Implementation, Strings.

**Comment by Hariprasad19036** [comment]
I would like to work on this issue, kindly assign this issue to me with hacktoberfest label. Thankyou!

**Comment by SarthakKeshari** [comment]
@Hariprasad19036,
Kindly add your solution to "codeforces" folder
Deadline - 03/10/2021

**Comment by Hariprasad19036** [comment]
@SarthakKeshari sir, I have added my solution in the "codeforces" folder and also opened a Pull Request. Kindly review and accept the same. Thanks in advance!
