### ISSUE TITLE
solution-quadratic

### ISSUE THREAD

**Issue by Phaneendra-Bottu** [SarthakKeshari/CPP-Questions-and-Solutions#17]
### Enter Issue id being referred to - #3 
Your answer

### Approach/Algorithm/Pseudo Code for the selected question - 
performing some mathematical functions

### Tags for the solution(eg - Array, Basic, Stack, etc.) - 
basic,sqrt function

**Comment by SarthakKeshari** [comment]
@Phaneendra-Bottu,
Kindly add your solution to Basic Codes folder
Deadline 27/09/2021
