### ISSUE TITLE
To Find a string is Lapindrome or Not

### ISSUE THREAD

**Issue by Zafershah24** [SarthakKeshari/CPP-Questions-and-Solutions#172]
### Enter your question - 
Lapindrome is defined as a string which when split in the middle, gives two halves having the same characters and same frequency of each character. If there are odd number of characters in the string, we ignore the middle character and check for lapindrome. For example gaga is a lapindrome, since the two halves ga and ga have the same characters with same frequency. Also, abccab, rotor and xyzxy are a few examples of lapindromes. Note that abbaab is NOT a lapindrome. The two halves contain the same characters but their frequencies do not match.
Your task is simple. Given a string, you need to tell if it is a lapindrome.

### Enter link to the question(if question belongs to any online platform) - 
https://www.codechef.com/problems/LAPIN

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Basic, Strings

**Comment by SarthakKeshari** [comment]
@Zafershah24,
Kindly fill the above Issue template.

**Comment by Zafershah24** [comment]
@SarthakKeshari Yes, I saw the template late, give me some time

**Comment by Zafershah24** [comment]
Kindly assign me this Issue. Thanks

**Comment by SarthakKeshari** [comment]
@Zafershah24,
Kindly add your solution to "codechef" folder
Deadline - 04/10/2021
