### ISSUE TITLE
Print the level order traversal of binary tree and print the left view and right view of binary tree

### ISSUE THREAD

**Issue by PrakharRathore123** [SarthakKeshari/CPP-Questions-and-Solutions#174]
### Enter your question - 
1)Print the level order traversal of binary tree .
2)Print the left view of binary tree. 
3) Print right view of binary tree.

### Enter link to the question(if question belongs to any online platform) - 
-

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Queue, Binary Tree , Recursion

**Comment by PrakharRathore123** [comment]
@SarthakKeshari Kindly issue me this problem

**Comment by SarthakKeshari** [comment]
@PrakharRathore123,
Kindly add your solution to "Data Structure/Trees/Binary Trees" folder.
Deadline - 04/10/2021
