### ISSUE TITLE
Print the Vertical order Traversal of Binary tree and Print the top view and bottom view of binary tree.

### ISSUE THREAD

**Issue by PrakharRathore123** [SarthakKeshari/CPP-Questions-and-Solutions#175]
### Enter your question - 
1)Print the vertical order Traversal of Binary tree.
2) Print the top view of binary tree. 
3)Print the Bottom view of binary tree.

### Enter link to the question(if question belongs to any online platform) - 
-

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Recursion , Queue , Binary tree

**Comment by PrakharRathore123** [comment]
@SarthakKeshari Kindly issue me this problem.

**Comment by SarthakKeshari** [comment]
@PrakharRathore123,
Kindly add your solution to "Data Structure/Trees/Binary Trees" folder.
Deadline - 04/10/2021
