### ISSUE TITLE
Create k stacks in a single array

### ISSUE THREAD

**Issue by mack611** [SarthakKeshari/CPP-Questions-and-Solutions#177]
### Enter your question - 
Create k stacks in a array using dynamic memory.

### Enter link to the question(if question belongs to any online platform) - 
No

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Stack,array,function

**Comment by mack611** [comment]
@SarthakKeshari pls assign me this

**Comment by SarthakKeshari** [comment]
@mack611,
Kindly add your solution to "Data Structure/Stack" folder
Deadline - 03/10/2021
