### ISSUE TITLE
DETECT LOOP IN SINGLY LINKED LIST

### ISSUE THREAD

**Issue by Prajakta102** [SarthakKeshari/CPP-Questions-and-Solutions#179]
### Enter your question - 
Your answer
check if loop is present in linked list or not.

### Enter link to the question(if question belongs to any online platform) - 
Your answer

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Your answer
#Linked list

**Comment by SarthakKeshari** [comment]
@Prajakta102,
Kindly add your solution to "Data Structure/Linked List/Single Linked List" folder
Deadline - 04/10/2021

**Comment by Prajakta102** [comment]
can i make one more pull request

**Comment by SarthakKeshari** [comment]
> can i make one more pull request

@Prajakta102,
For sure
