### ISSUE TITLE
XOR Equal

### ISSUE THREAD

**Issue by kartik-ey1** [SarthakKeshari/CPP-Questions-and-Solutions#182]
### Enter your question - 
You are given an array A consisting of N integers and an integer X. Your goal is to have as many equal integers as possible in the array. To achieve this goal, you can do the following operation:

Choose an index i (1≤i≤N) and set Ai=Ai⊕X, where ⊕ denotes the bitwise xor operation.
Find the maximum number of equal integers you can have in the final array and the minimum number of operations to obtain these many equal integers

### Enter link to the question(if question belongs to any online platform) - 
https://www.codechef.com/SEPT21C/problems/PALINT

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
maps , array , XOR bitwise operater ,math skills

**Comment by SarthakKeshari** [comment]
@kartik-ey1,
Kindly add your solution to "codechef" folder
Deadline - 04/10/2021

**Comment by kartik-ey1** [comment]
I WANT TO CONTRIBUTE IN THIS 
CAN YOU PLEASE ASSIGN ME  @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@kartik-ey1,
Kindly add your solution to "codechef" folder
Deadline - 04/10/2021
