### ISSUE TITLE
Repeated DNA Sequences

### ISSUE THREAD

**Issue by ThejaswinS** [SarthakKeshari/CPP-Questions-and-Solutions#184]
### Enter your question - 
The DNA sequence is composed of a series of nucleotides abbreviated as 'A', 'C', 'G', and 'T'.

For example, "ACGAATTCCG" is a DNA sequence.
When studying DNA, it is useful to identify repeated sequences within the DNA.

Given a string s that represents a DNA sequence, return all the 10-letter-long sequences (substrings) that occur more than once in a DNA molecule. You may return the answer in any order.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/repeated-dna-sequences/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Strings, Arrays

Kindly pls assign me this issue.
Hactoberfest2021

**Comment by SarthakKeshari** [comment]
@ThejaswinS,
Kindly add your solution to "leetcode" folder
Deadline - 04/10/2021
