### ISSUE TITLE
Check Wether a Number is power of 4 or not using Bit Manipulation

### ISSUE THREAD

**Issue by ujju20** [SarthakKeshari/CPP-Questions-and-Solutions#185]
### Enter your question - 
Given an integer n, return true if it is a power of four. Otherwise, return false.

An integer n is a power of four, if there exists an integer x such that n == 4^x.

### Enter link to the question(if question belongs to any online platform) - 
[Power of 4](https://leetcode.com/problems/power-of-four/)

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
BitManipulation, Math

**Comment by SarthakKeshari** [comment]
@ujju20,
Kindly add your solution to "leetcode" folder.
Deadline - 03/10/2021

Gentle advice for futher Issues -
Medium and hard level questions will be given preference for Hacktoberfest tag.

**Comment by satyam-mahajan** [comment]
Hii , I am able to fix the issue in a optimal way. Please assign to me.
Thanking you...!!!

**Comment by SarthakKeshari** [comment]
@satyam-mahajan,
Kindly refer CONTRIBUTING.md
