### ISSUE TITLE
Array Optimization by Deque

### ISSUE THREAD

**Issue by rohitkumar9710** [SarthakKeshari/CPP-Questions-and-Solutions#186]
### Enter your question - 
You are given an integer array a[1…n]=[a1,a2,…,an].

Let us consider an empty deque (double-ended queue). A deque is a data structure that supports adding elements to both the beginning and the end. So, if there are elements [3,4,4] currently in the deque, adding an element 1 to the beginning will produce the sequence [1,3,4,4], and adding the same element to the end will produce [3,4,4,1].

The elements of the array are sequentially added to the initially empty deque, starting with a1 and finishing with an. Before adding each element to the deque, you may choose whether to add it to the beginning or to the end.

For example, if we consider an array a=[3,7,5,5], one of the possible sequences of actions looks like this:
 1.	add 3 to the beginning of the deque:	deque has a sequence [3] in it;
 2.	add 7 to the end of the deque:	deque has a sequence [3,7] in it;
 3.	add 5 to the end of the deque:	deque has a sequence [3,7,5] in it;
 4.	add 5 to the beginning of the deque:	deque has a sequence [5,3,7,5] in it;

Find the minimal possible number of inversions in the deque after the whole array is processed.

An inversion in sequence d is a pair of indices (i,j) such that i<j and di>dj. For example, the array d=[5,3,7,5] has exactly two inversions — (1,2) and (3,4), since d1=5>3=d2 and d3=7>5=d4.

### Enter link to the question(if question belongs to any online platform) - 
https://codeforces.com/contest/1579/problem/E2

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
data-structures, greedy, hard

**Comment by SarthakKeshari** [comment]
@rohitkumar9710,
Kindly add your solution to "codeforces" folder.
Deadline - 04/10/2021
