### ISSUE TITLE
Print Left view of binary tree(iterative approach)

### ISSUE THREAD

**Issue by Prajakta102** [SarthakKeshari/CPP-Questions-and-Solutions#187]
### Enter your question - 
Your answer
Given a binary tree, write an efficient algorithm to print its left view.

### Enter link to the question(if question belongs to any online platform) - 
Your answer

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Your answer
Binary tree,list,queue

**Comment by Prajakta102** [comment]
Kindly assign this task to me.

**Comment by SarthakKeshari** [comment]
@Prajakta102,
Kindly add your solution to "Data Structure/Trees/Binary Trees" folder
Deadline - 04/10/2021
