### ISSUE TITLE
Implemetation of heap using Vector

### ISSUE THREAD

**Issue by ujju20** [SarthakKeshari/CPP-Questions-and-Solutions#189]
### Enter your question - 
Implement heap data structure using array.

### Enter link to the question(if question belongs to any online platform) - 
NA

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Heap, Array, Recursion

**Comment by SarthakKeshari** [comment]
@ujju20,
Kindly add your solution to "Data Structure/Heap" folder.
Deadline - 04/10/2021
