### ISSUE TITLE
Swap 1

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/CPP-Questions-and-Solutions#19]
### Enter your question - 
Write a program to swap two numbers (with the help of third variable).

### Enter link to the question(if question belongs to any online platform) - 
No Link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Basic

**Comment by Phaneendra-Bottu** [comment]
I would like to solve this please assign this issue to me

**Comment by SarthakKeshari** [comment]
@Phaneendra-Bottu,
Go ahead and kindly place your solution in "Basic Codes" folder.
Deadline 29/09/2021
