### ISSUE TITLE
Kadane's Algorithm

### ISSUE THREAD

**Issue by tanishagarg1803** [SarthakKeshari/CPP-Questions-and-Solutions#193]
### Enter your question - 
Kadane's Algorithm 
Medium Accuracy: 51.0% Submissions: 100k+ Points: 4
Given an array Arr[] of N integers. Find the contiguous sub-array(containing at least one number) which has the maximum sum and return its sum.

Example 1:

Input:
N = 5
Arr[] = {1,2,3,-2,5}
Output:
9
Explanation:
Max subarray sum is 9
of elements (1, 2, 3, -2, 5) which 
is a contiguous subarray.
Example 2:

Input:
N = 4
Arr[] = {-1,-2,-3,-4}
Output:
-1
Explanation:
Max subarray sum is -1 
of element (-1)

Your Task:
You don't need to read input or print anything. The task is to complete the function maxSubarraySum() which takes Arr[] and N as input parameters and returns the sum of subarray with maximum sum.

Expected Time Complexity: O(N)
Expected Auxiliary Space: O(1)

Constraints:
1 ≤ N ≤ 106
-107 ≤ A[i] ≤ 107

### Enter link to the question(if question belongs to any online platform) - 
https://practice.geeksforgeeks.org/problems/kadanes-algorithm-1587115620/1/?problemStatus=solved&difficulty[]=1&difficulty[]=2&page=1&query=problemStatussolveddifficulty[]1difficulty[]2page1

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Arrays , Dynamic Programming , Algorithms

Your answer

**Comment by tanishagarg1803** [comment]
I am working for hacktoberfest 2021.
Please assign this issue to me.
Thankyou!

**Comment by SarthakKeshari** [comment]
@tanishagarg1803,
Kindly add your solution to "GeeksForGeeks" folder
Deadline - 04/10/2021
