### ISSUE TITLE
Jump Game

### ISSUE THREAD

**Issue by Ritwik009** [SarthakKeshari/CPP-Questions-and-Solutions#197]
### Enter your question - 
You are given an integer array nums. You are initially positioned at the array's first index, and each element in the array represents your maximum jump length at that position.

Return true if you can reach the last index, or false otherwise.

 

Example 1:

Input: nums = [2,3,1,1,4]
Output: true
Explanation: Jump 1 step from index 0 to 1, then 3 steps to the last index.
Example 2:

Input: nums = [3,2,1,0,4]
Output: false
Explanation: You will always arrive at index 3 no matter what. Its maximum jump length is 0, which makes it impossible to reach the last index.
 

Constraints:

1 <= nums.length <= 104
0 <= nums[i] <= 105

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/jump-game/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Greedy, Dynamic Programming

**Comment by Ritwik009** [comment]
@SarthakKeshari Kindly assign this issue to me.

**Comment by SarthakKeshari** [comment]
@Ritwik009,
Go ahead, Kindly add your solution to "leet code" folder.
Deadline - 04/10/2021
