### ISSUE TITLE
Maximum HourGlass Sum 2D Array.

### ISSUE THREAD

**Issue by iammohit07** [SarthakKeshari/CPP-Questions-and-Solutions#198]
### Enter your question - 
Given a 2D Array of 6 x 6 :
1 1 1 0 0 0
0 1 0 0 0 0
1 1 1 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
An hourglass is a subset of values with indices falling in this pattern in this graphical representation.
There are 16 hourglasses in array . An hourglass sum is the sum of an hourglass' values. Calculate the hourglass sum for every hourglass in array, then print the maximum hourglass sum. The array will always be 6 x 6.

### Enter link to the question(if question belongs to any online platform) - 
https://www.hackerrank.com/challenges/2d-array/problem

#### Data Structures
-  Array

**Comment by ayushjindal23** [comment]
I know how to do this question. Can you assign it to me?

**Comment by SarthakKeshari** [comment]
@ayushjindal23,
Kindly add your solution to "hackerrank" folder.
Deadline - 04/10/2021

**Comment by ayushjindal23** [comment]
@SarthakKeshari I have created the pull request. #256
