### ISSUE TITLE
C. Less or Equal

### ISSUE THREAD

**Issue by pptsagar279** [SarthakKeshari/CPP-Questions-and-Solutions#199]
### Enter your question - 
You are given a sequence of integers of length n and integer number k. You should print any integer number x in the range of [1;109] (i.e. 1≤x≤109) such that exactly k elements of given sequence are less than or equal to x.

Note that the sequence can contain equal elements.

If there is no such x, print "-1" (without quotes).

### Enter link to the question(if question belongs to any online platform) - 
[https://codeforces.com/problemset/problem/977/C](https://codeforces.com/problemset/problem/977/C)

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Sorting

**Comment by Anujkumar2017** [comment]
pls assign me

**Comment by SarthakKeshari** [comment]
@Anujkumar2017,
Kindly add your solution to "codeforces" folder
Deadline - 04/10/2021

**Comment by Anujkumar2017** [comment]
Hi, Kindly review and merge my PR #235.
