### ISSUE TITLE
Swap 2

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/CPP-Questions-and-Solutions#20]
### Enter your question - 
Write a program to swap two numbers (WITHOUT the help of third variable).

### Enter link to the question(if question belongs to any online platform) - 
No Link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Basic

**Comment by MohammedHassan07** [comment]
I want to solve this please assign this issue to me

**Comment by SarthakKeshari** [comment]
@MohammedHassan07,
Go ahead and kindly place your solution in "Basic Codes" folder.
Deadline 29/09/2021

**Comment by MohammedHassan07** [comment]
I have written the code, but how to upload it on the basic code folder

**Comment by SarthakKeshari** [comment]
It seems you haven't forked the repo

**Comment by SarthakKeshari** [comment]
Follow an online video or a blog on how to contribute on open source projects
In case you still face issue contact me @ - srthkkeshari84@gmail.com

**Comment by MohammedHassan07** [comment]
I forked and clone the repo, what to do next, please guide me, I am a beginner

**Comment by SarthakKeshari** [comment]
@MohammedHassan07,
Are you facing any issue?

**Comment by MohammedHassan07** [comment]
When I execute the command git push upstream it through the error. @SarthakKeshari

**Comment by Vedika-Agrawal** [comment]
Sir I also would like to work on this issue, please assign this issue to me!

**Comment by sej28** [comment]
I would like to do this, please assign me

**Comment by SarthakKeshari** [comment]
Hello all present on this issue,
Once the deadline is over after that I can assign it to anyone else.

There are three methods how you can contribute to this repository - 
1) Add a question and provide the solution for the same
2) Provide a solution
3) Add a question

Kindly go through CONTRIBUTING.md file for complete details
This is always the first step for all open source contributor. 
I am going to add more questions too, so read it and come back and claim your question.
