### ISSUE TITLE
B. Ternary String

### ISSUE THREAD

**Issue by pptsagar279** [SarthakKeshari/CPP-Questions-and-Solutions#200]
### Enter your question - 
You are given a string s such that each its character is either 1, 2, or 3. You have to choose the shortest contiguous substring of s such that it contains each of these three characters at least once.

A contiguous substring of string s is a string that can be obtained from s by removing some (possibly zero) characters from the beginning of s and some (possibly zero) characters from the end of s.

### Enter link to the question(if question belongs to any online platform) - 
[https://codeforces.com/problemset/problem/1354/B](https://codeforces.com/problemset/problem/1354/B)

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Binary Search, DP, Implementation, Two Pointers

**Comment by Anujkumar2017** [comment]
please assign me

**Comment by SarthakKeshari** [comment]
@Anujkumar2017,
Kindly add your solution to "codeforces" folder.
Deadline - 06/10/2021
