### ISSUE TITLE
Median of Two Sorted Arrays of Different Sizes

### ISSUE THREAD

**Issue by ujju20** [SarthakKeshari/CPP-Questions-and-Solutions#201]
### Enter your question - 
Given two sorted arrays array1 and array2 of size m and n respectively. Find the median of the two sorted arrays in the best time complexity.

### Enter link to the question(if question belongs to any online platform) - 
https://practice.geeksforgeeks.org/problems/median-of-2-sorted-arrays-of-different-sizes/1#

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Arrays, Searching

**Comment by SarthakKeshari** [comment]
@ujju20,
More than 2 issues can't be assiged to the same contributor at a time.

**Comment by tausiq2003** [comment]
can I wok on this

**Comment by SarthakKeshari** [comment]
@tausiq2003,
Kindly add your solution to "GeeksForGeeks" folder
Deadline - 05/10/2021

**Comment by tausiq2003** [comment]
ok i will

**Comment by satyam-mahajan** [comment]
Hii , I am able to fix the issue in a optimal way. Please assign to me.
Thanking you...!!!

**Comment by tausiq2003** [comment]
I have already been assigned if I am unable to submit then you will

**Comment by tausiq2003** [comment]
Can I do it using C

**Comment by SarthakKeshari** [comment]
> Can I do it using C

Its outside the scope of this Repo

**Comment by ujju20** [comment]
> @tausiq2003, Kindly add your solution to "GeeksForGeeks" folder Deadline - 05/10/2021

Can I take this issue now Deadline has reached and he hasn't completed his work?

**Comment by tausiq2003** [comment]
wait a minute

**Comment by tausiq2003** [comment]
another 3 hours left

**Comment by tausiq2003** [comment]
I will do it

**Comment by tausiq2003** [comment]
i will submit a solution which may not match  the geeksforgeeks but its done in diff way.

**Comment by SarthakKeshari** [comment]
> i will submit a solution which may not match the geeksforgeeks but its done in diff way.

@tausiq2003,
A different approach is always appreciated. P

**Comment by tausiq2003** [comment]
> > i will submit a solution which may not match the geeksforgeeks but its done in diff way.
> 
> @tausiq2003, A different approach is always appreciated.
Yeah review it and merge it.
