### ISSUE TITLE
Job Sequencing Problem

### ISSUE THREAD

**Issue by ujju20** [SarthakKeshari/CPP-Questions-and-Solutions#202]
### Enter your question - 
Given a set of N jobs where each job has a deadline and profit associated with it. Each job takes 1 unit of time to complete and only one job can be scheduled at a time. We earn the profit if and only if the job is completed by its deadline. The task is to find the number of jobs done and the maximum profit.

### Enter link to the question(if question belongs to any online platform) - 
https://practice.geeksforgeeks.org/problems/job-sequencing-problem-1587115620/1#

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Greedy, Dynamic Programming

**Comment by SarthakKeshari** [comment]
@ujju20,
Kindly add your solution to "GeeksForGeeks" folder.
Deadline - 04/10/2021

**Comment by ayushjindal23** [comment]
@SarthakKeshari Can I have this problem too? I would really like to work on it.

**Comment by SarthakKeshari** [comment]
@ayushjindal23,
Same question should not be repeated
