### ISSUE TITLE
K-th element of two sorted Arrays

### ISSUE THREAD

**Issue by ujju20** [SarthakKeshari/CPP-Questions-and-Solutions#203]
### Enter your question - 
Given two sorted arrays arr1 and arr2 of size N and M respectively and an element K. The task is to find the element that would be at the k’th position of the final sorted array.
 

### Enter link to the question(if question belongs to any online platform) - 
https://practice.geeksforgeeks.org/problems/k-th-element-of-two-sorted-array1317/1

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
 Arrays, Divide and Conquer

**Comment by SarthakKeshari** [comment]
@ujju20,
Kindly add your solution to "GeeksForGeeks" folder.
Deadline - 04/10/2021

**Comment by Vishwajith-Shettigar** [comment]
could you assign me

**Comment by SarthakKeshari** [comment]
@Vishwajith-Shettigar,
Kindly create a new issue and claim it.
This issue is already assigned. 
Refer CONTRIBUTING.md for further details
