### ISSUE TITLE
Sort and Print the Boundary Elements of a 2D Matrix 

### ISSUE THREAD

**Issue by abhilashkpy** [SarthakKeshari/CPP-Questions-and-Solutions#212]
### Enter your question - 
Write a program in Java to sort the boundary elements of a Two Dimensional Matrix and print the sorted and original matrices.

**Constraints:** The program MUST take input from the user for the dimensions of the matrix.

### Enter link to the question(if question belongs to any online platform) - 
N/A

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Basic

**Comment by SarthakKeshari** [comment]
@abhilashkpy,
Kindly add your solution to "Arrays/2D Arrays" folder
Deadline - 04/10/2021

**Comment by abhilashkpy** [comment]
I am unable to get the tag of issue #212 while filling out the PR template

**Comment by Karan0009** [comment]
hello,kindly assign me this issue if it's still open
