### ISSUE TITLE
Turn_the_Rectangles

### ISSUE THREAD

**Issue by Master-Helix** [SarthakKeshari/CPP-Questions-and-Solutions#214]
### Enter your question - 
There are n rectangles in a row. You can either turn each rectangle by 90 degrees or leave it as it is. If you turn a rectangle, its width will be height, and its height will be width. Notice that you can turn any number of rectangles, you also can turn all or none of them. You can not change the order of the rectangles.

Find out if there is a way to make the rectangles go in order of non-ascending height. In other words, after all the turns, a height of every rectangle has to be not greater than the height of the previous rectangle (if it is such).

**Input**
The first line contains a single integer n (1≤n≤105) — the number of rectangles.

Each of the next n lines contains two integers wi and hi (1≤wi,hi≤109) — the width and the height of the i-th rectangle.

**Output**
Print "YES" (without quotes) if there is a way to make the rectangles go in order of non-ascending height, otherwise print "NO".

You can print each letter in any case (upper or lower).

### Enter link to the question(if question belongs to any online platform) - 
https://codeforces.com/contest/1008/problem/B

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Greedy, Sortings, 1000 (Rating on Codeforces)

**Comment by Master-Helix** [comment]
@SarthakKeshari  Sir, kindly assign this question to me.
Thank You

**Comment by SarthakKeshari** [comment]
@Master-Helix,
Kindly add your solution to "codeforces" folder.
Deadline - 04/10/2021
