### ISSUE TITLE
[Selection Sort]

### ISSUE THREAD

**Issue by SwarnimaShishodia** [SarthakKeshari/CPP-Questions-and-Solutions#216]
### Enter your question - 
Selection sort implementation

### Enter link to the question(if question belongs to any online platform) - 
Your answer

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array Sorting Basic

**Comment by SwarnimaShishodia** [comment]
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
@SwarnimaShishodia,
Go ahead, Kindly add your solution to "Sorting" folder.
Deadline - 04/10/2021
