### ISSUE TITLE
[Bubble Sort]

### ISSUE THREAD

**Issue by SwarnimaShishodia** [SarthakKeshari/CPP-Questions-and-Solutions#217]
### Enter your question - 
Bubble Sort implementation

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array Sorting Basic

**Comment by SwarnimaShishodia** [comment]
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
@SwarnimaShishodia,
Go ahead, Kindly add your solution to "Sorting" folder.
Deadline - 04/10/2021
