### ISSUE TITLE
Insertion sort

### ISSUE THREAD

**Issue by SwarnimaShishodia** [SarthakKeshari/CPP-Questions-and-Solutions#218]
### Enter your question - 
Insertion sort implementation

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array Sorting Basic

**Comment by SwarnimaShishodia** [comment]
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
@SwarnimaShishodia,
Kindly note more than 2 issues cannot be assigned at a time.

**Comment by AyushAgrawal25** [comment]
@SarthakKeshari  can u please assign this to me.

**Comment by Sahilnegi-code** [comment]
Can u  pls assign me this issue

**Comment by SarthakKeshari** [comment]
@AyushAgrawal25,
Kindly add your solution to "Sorting" folder.
Deadline - 04/10/2021
