### ISSUE TITLE
Merge Sort

### ISSUE THREAD

**Issue by SwarnimaShishodia** [SarthakKeshari/CPP-Questions-and-Solutions#219]
### Enter your question - 
Merge Sort Implementation

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Recursion Array Basic Sorting

**Comment by SwarnimaShishodia** [comment]
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
@SwarnimaShishodia,
Kindly note more than 2 issues cannot be assigned at a time.

**Comment by LikhithaTadikonda** [comment]
@SwarnimaShishodia please assign this to me :)

**Comment by SwarnimaShishodia** [comment]
@LikhithaTadikonda Only @SarthakKeshari can assign to you.

> @SwarnimaShishodia please assign this to me :)

**Comment by ayushjindal23** [comment]
@SarthakKeshari I have experience in cpp and sorting techniques. Can you assign this to me?

**Comment by SarthakKeshari** [comment]
@ayushjindal23,
Kindly add your solution to "Sorting" folder
Deadline - 04/10/2021
