### ISSUE TITLE
Find the Sum of all nodes at given level of Binary tree.

### ISSUE THREAD

**Issue by PrakharRathore123** [SarthakKeshari/CPP-Questions-and-Solutions#224]
### Enter your question - 
You are given a number representing the level number you have to determine the sum of all nodes at that level.

### Enter link to the question(if question belongs to any online platform) - 
-

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Queue , Recursion , Binary tree

**Comment by SarthakKeshari** [comment]
@PrakharRathore123,
Kindly add you solution to "Data Structure/Trees/Binary Trees" folder
Deadline - 04/10/2021
