### ISSUE TITLE
1232. Check If It Is a Straight Line

### ISSUE THREAD

**Issue by Anujkumar2017** [SarthakKeshari/CPP-Questions-and-Solutions#225]
### Enter your question - 
You are given an array coordinates, coordinates[i] = [x, y], where [x, y] represents the coordinate of a point. Check if these points make a straight line in the XY plane.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/check-if-it-is-a-straight-line/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Math, Array, Geometry

**Comment by SarthakKeshari** [comment]
@Anujkumar2017,
KIndly add your solution to "leetcode" folder
Deadline - 04/10/2021

Gentle advice for futher Issues -
Medium and hard level questions will be given preference for Hacktoberfest tag.

**Comment by Anujkumar2017** [comment]
Hi, Kindly review and merge my PR #208 .

**Comment by Anujkumar2017** [comment]
Hi, kindly review and merge my PR #254
 Ignore the previous PR(#208)
