### ISSUE TITLE
Factorial 1

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/CPP-Questions-and-Solutions#23]
### Enter your question - 
Write a program to find factorial of a number entered by the user. (Using loop)

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Basic, loops

**Comment by BodaleDenis** [comment]
Hi, I would like to work in this one, can I be assigned?

**Comment by SarthakKeshari** [comment]
@BodaleDenis,
Kindly add your solution to "Basic Codes" folder.
Deadline - 30/09/2021

**Comment by gb07bh** [comment]
Sir, I would love to work on this one, can I be assigned to work on this?

**Comment by SarthakKeshari** [comment]
@gb07bh,
It already assigned wait for the deadline to be over or what best you can do is go ahead and create a new issue

**Comment by gb07bh** [comment]
Sure, Sir, I would wait for the deadline and then be assigned on this.
