### ISSUE TITLE
Calculate the Number of Nodes, Sum of Nodes , height , diameter of Binary Tree.

### ISSUE THREAD

**Issue by PrakharRathore123** [SarthakKeshari/CPP-Questions-and-Solutions#231]
### Enter your question - 
1) Calculate the Number of Nodes of Binary Tree
2) Sum of Nodes of Binary Tree
3) Height of Binary Tree
4) Diameter of Binary Tree 

### Enter link to the question(if question belongs to any online platform) - 
-

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Binary Tree , Recursion .

**Comment by Blankita21** [comment]
Kindly assign me this issue.

**Comment by PrakharRathore123** [comment]
@SarthakKeshari Kindly issue me this problem.

**Comment by SarthakKeshari** [comment]
@Blankita21,
Kindly add your solution to "Data Structure/Trees/ Binary Trees" folder
Deadline - 04/10/2021

**Comment by Blankita21** [comment]
Just to confirm, I have to make separate files for all the problems right?

**Comment by SarthakKeshari** [comment]
@Blankita21,
Different files
