### ISSUE TITLE
Sum Replacement.

### ISSUE THREAD

**Issue by PrakharRathore123** [SarthakKeshari/CPP-Questions-and-Solutions#232]
### Enter your question - 
Given a Binary Tree where each node has value. Convert this to a tree where each node contains the sum of the left and right sub trees in the original tree.

### Enter link to the question(if question belongs to any online platform) - 
-

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Binary Tree , Recursion

**Comment by PrakharRathore123** [comment]
@SarthakKeshari Kindly issue me this problem.

**Comment by Blankita21** [comment]
Kindly assign me this issue.

**Comment by SarthakKeshari** [comment]
@PrakharRathore123,
Kindly add your solution to "" folder.
Deadline - 04/10/2021
