### ISSUE TITLE
Non-Decreasing Dilemma || codeforces

### ISSUE THREAD

**Issue by Aakash-Raj-2001** [SarthakKeshari/CPP-Questions-and-Solutions#233]
### Enter your question - 
Alice has recently received an array a1,a2,…,an for her birthday! She is very proud of her array, and when she showed her friend Bob the array, he was very happy with her present too!

However, soon Bob became curious, and as any sane friend would do, asked Alice to perform q operations of two types on her array:

1 x y: update the element ax to y (set ax=y).
2 l r: calculate how many non-decreasing subarrays exist within the subarray [al,al+1,…,ar]. More formally, count the number of pairs of integers (p,q) such that l≤p≤q≤r and ap≤ap+1≤⋯≤aq−1≤aq.
Help Alice answer Bob's queries!

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Data Structures , divide and conquer , array

**Comment by Aakash-Raj-2001** [comment]
@SarthakKeshari Can you assign me this issue ?

**Comment by Blankita21** [comment]
Kindly assign me this issue.

**Comment by SarthakKeshari** [comment]
@Aakash-Raj-2001,
Kindly add your solution to "codeforces" folder.
Deadline - 04/10/2021
