### ISSUE TITLE
House Robber | LeetCode Medium Level Problem

### ISSUE THREAD

**Issue by baranwal** [SarthakKeshari/CPP-Questions-and-Solutions#242]
### Enter your question - 
You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed, the only constraint stopping you from robbing each of them is that adjacent houses have security systems connected and it will automatically contact the police if two adjacent houses were broken into on the same night.

Given an integer array nums representing the amount of money of each house, return the maximum amount of money you can rob tonight without alerting the police.

### Enter link to the question(if question belongs to any online platform) - 
[LeetCode House Robber Problem Link](https://leetcode.com/problems/house-robber/)

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Dynamic Programming

**Comment by baranwal** [comment]
Please assign this to me.

**Comment by SarthakKeshari** [comment]
@baranwal,
Kindly add your solution to "leetcode" folder.
Deadline - 05/10/2021

**Comment by satyam-mahajan** [comment]
Hii , I am able to fix the issue in a optimal way. Please assign to me.
Thanking you...!!!

**Comment by SarthakKeshari** [comment]
@satyam-mahajan,
Kindly refer CONTRIBUTING.md to find how you can contribute and other guidelines.
