### ISSUE TITLE
[LeetCode problem]: Trapping Rain Water

### ISSUE THREAD

**Issue by pratikj697** [SarthakKeshari/CPP-Questions-and-Solutions#243]
### Enter your question - 
Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/trapping-rain-water/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
leetcode, trapping rain water, dsa

**Comment by pratikj697** [comment]
Please assign me this issue for solution

**Comment by SarthakKeshari** [comment]
@pratikj697,
Kindly add your solution to "leetcode" folder
Deadline - 05/10/2021

**Comment by SarthakKeshari** [comment]
Plagarized PR submitted - https://scaryrival.blogspot.com/2021/06/sbt-daily-test-10-jun-tech-mcq-code.html
