### ISSUE TITLE
Hotel Prices || Intermediate 

### ISSUE THREAD

**Issue by Harshit-Poddar90** [SarthakKeshari/CPP-Questions-and-Solutions#244]
### Enter your question - 
In this challenge, the task is to debug the existing code to successfully execute all provided test files.

The given code defines two classes Hotel Room and Hotel Apartment denoting respectively a standard hotel room and a hotel apartment. An instance of any of these classes has two parameters: bedrooms and bathrooms denoting respectively the number of bedrooms and the number of bathrooms in the room.

The prices of a standard hotel room and hotel apartment are given as:

Hotel Room:  50 bedrooms + 100 . bathrooms
Hotel Apartment: The price of a standard room with the same number bedrooms and bathrooms plus 100
For example, if a standard room costs 200 then an apartment with the same number of bedrooms and bathrooms costs 300

In hotel's codebase, there is a piece of code reading the list of rooms booked for today and calculates the total profit for the hotel. However, sometimes calculated profits are lower than they should be.

Debug the existing Hotel Room and Hotel Apartment classes' implementations so that the existing code computing the total profit returns a correct profit.

Your function will be tested against several cases by the locked template code.

### Enter link to the question(if question belongs to any online platform) - 

https://www.hackerrank.com/challenges/hotel-prices/problem
### Tags for the question(eg - Array, Basic, Stack, etc.) - 
loops etc.

**Comment by Harshit-Poddar90** [comment]
pls assign it to me

**Comment by SarthakKeshari** [comment]
@Harshit-Poddar90,
Kindly add your solution to "hackerrank" folder
Deadline - 05/10/2021
