### ISSUE TITLE
412. Fizz Buzz

### ISSUE THREAD

**Issue by Anujkumar2017** [SarthakKeshari/CPP-Questions-and-Solutions#255]
### Enter your question - 
Given an integer n, return a string array answer (1-indexed) where:

answer[i] == "FizzBuzz" if i is divisible by 3 and 5.
answer[i] == "Fizz" if i is divisible by 3.
answer[i] == "Buzz" if i is divisible by 5.
answer[i] == i if non of the above conditions are true.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/fizz-buzz/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Math, String

**Comment by Anujkumar2017** [comment]
please assign me sir

**Comment by SarthakKeshari** [comment]
@Anujkumar2017,
Kindly add your solution to "leetcode" folder.
Deadline - 05/10/2021

This Issue will only be counted towards ranking criteria of this repository.

Gentle advice for futher Issues -
Medium and hard level questions will be given preference for Hacktoberfest tag.
