### ISSUE TITLE
1281. Subtract the Product and Sum of Digits of an Integer

### ISSUE THREAD

**Issue by Anujkumar2017** [SarthakKeshari/CPP-Questions-and-Solutions#257]
### Enter your question - 
Given an integer number n, return the difference between the product of its digits and the sum of its digits.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/subtract-the-product-and-sum-of-digits-of-an-integer/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Math

**Comment by Anujkumar2017** [comment]
please assign me sir

**Comment by SarthakKeshari** [comment]
@Anujkumar2017,
Kindly add your solution to "leetcode" folder.
Deadline - 05/10/2021

This Issue will only be counted towards ranking criteria of this repository.

Gentle advice for futher Issues -
Medium and hard level questions will be given preference for Hacktoberfest tag.
