### ISSUE TITLE
Minimum Platforms

### ISSUE THREAD

**Issue by ujju20** [SarthakKeshari/CPP-Questions-and-Solutions#260]
### Enter your question - 
Given arrival and departure times of all trains that reach a railway station. Find the minimum number of platforms required for the railway station so that no train is kept waiting.
Consider that all the trains arrive on the same day and leave on the same day. Arrival and departure time can never be the same for a train but we can have arrival time of one train equal to departure time of the other. At any given instance of time, same platform can not be used for both departure of a train and arrival of another train. In such cases, we need different platforms.

### Enter link to the question(if question belongs to any online platform) - 
https://practice.geeksforgeeks.org/problems/minimum-platforms-1587115620/1

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Greedy

**Comment by ayushjindal23** [comment]
I would love to try this problem

**Comment by ujju20** [comment]
> I would love to try this problem

Kindly Make your own issue and then solve them.
This issue is created by me and I am working on this.

**Comment by SarthakKeshari** [comment]
@ujju20,
Kindly wait for the issue to be assigned to you before creating the PR.
