### ISSUE TITLE
Magic Spells || Hard

### ISSUE THREAD

**Issue by Harshit-Poddar90** [SarthakKeshari/CPP-Questions-and-Solutions#263]
### Enter your question - 
While playing a video game, you are battling a powerful dark wizard. He casts his spells from a distance, giving you only a few seconds to react and conjure your counterspells. For a counterspell to be effective, you must first identify what kind of spell you are dealing with.

The wizard uses scrolls to conjure his spells, and sometimes he uses some of his generic spells that restore his stamina. In that case, you will be able to extract the name of the scroll from the spell. Then you need to find out how similar this new spell is to the spell formulas written in your spell journal.

Spend some time reviewing the locked code in your editor, and complete the body of the counterspell function.

Check Dynamic cast to get an idea of how to solve this challenge.

### Enter link to the question(if question belongs to any online platform) - 
https://www.hackerrank.com/challenges/magic-spells/problem

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Full application based.

**Comment by Harshit-Poddar90** [comment]
pls assign it to me

**Comment by SarthakKeshari** [comment]
@Harshit-Poddar90,
Kindly add your solution to "hackerrank" folder.
Deadline - 06/10/2021
