### ISSUE TITLE
Reverse Nodes in k-Group

### ISSUE THREAD

**Issue by sksukruth** [SarthakKeshari/CPP-Questions-and-Solutions#265]
### Enter your question - 
Given a linked list, reverse the nodes of a linked list k at a time and return its modified list.
k is a positive integer and is less than or equal to the length of the linked list. If the number of nodes is not a multiple of k then left-out nodes, in the end, should remain as it is.
You may not alter the values in the list's nodes, only nodes themselves may be changed.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/reverse-nodes-in-k-group/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Linked List

**Comment by SarthakKeshari** [comment]
@sksukruth,
Kindly add your solution to "leetcode" folder.
Deadline - 05/10/2021
