### ISSUE TITLE
45. Jump Game II  | Leetcode

### ISSUE THREAD

**Issue by Abhishekgaikwadcoder** [SarthakKeshari/CPP-Questions-and-Solutions#269]
### Enter your question - 

Given an array of non-negative integers nums, you are initially positioned at the first index of the array.

Each element in the array represents your maximum jump length at that position.

Your goal is to reach the last index in the minimum number of jumps.

You can assume that you can always reach the last index.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/jump-game-ii/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Dynamic programming, Greedy

**Comment by Abhishekgaikwadcoder** [comment]
@SarthakKeshari  Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
@Abhishekgaikwadcoder,
Kindly add your solution to "leetcode" folder
Deadline - 05/10/2021
