### ISSUE TITLE
print prime nos upto 50

### ISSUE THREAD

**Issue by TirthPinkalSheth** [SarthakKeshari/CPP-Questions-and-Solutions#27]
### Enter your question - 
Write a program to print prime nos upto 50.

### Enter link to the question(if question belongs to any online platform) - 
no link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
basic mathematics and loops

**Comment by TirthPinkalSheth** [comment]
kindly assign issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@TirthPinkalSheth,
Kindly place your solution in "Basic Codes" folder
Deadline 29/09/2021
