### ISSUE TITLE
35. Search Insert Position

### ISSUE THREAD

**Issue by Anujkumar2017** [SarthakKeshari/CPP-Questions-and-Solutions#274]
### Enter your question - 
Your answerGiven a sorted array of distinct integers and a target value, return the index if the target is found. If not, return the index where it would be if it were inserted in order.

You must write an algorithm with O(log n) runtime complexity.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/search-insert-position/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Binary Search

**Comment by Anujkumar2017** [comment]
@SarthakKeshari 
Sir, please assign me.

**Comment by SarthakKeshari** [comment]
@Anujkumar2017,
Kindly add your solution to "leetcode" folder
Deadline - 05/10/2021
