### ISSUE TITLE
Three Boxes | THREEBOX

### ISSUE THREAD

**Issue by Anujkumar2017** [SarthakKeshari/CPP-Questions-and-Solutions#276]
### Enter your question - 
Chef has 3 boxes of sizes A, B, and C respectively. He puts the boxes in bags of size D (A≤B≤C≤D). Find the minimum number of bags Chef needs so that he can put each box in a bag. A bag can contain more than one box if the sum of sizes of boxes in the bag does not exceed the size of the bag.

### Enter link to the question(if question belongs to any online platform) - 
https://www.codechef.com/OCT21C/problems/THREEBOX

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Greedy

**Comment by Anujkumar2017** [comment]
@SarthakKeshari 
Sir, please assign me

**Comment by SarthakKeshari** [comment]
@Anujkumar2017,
Kindly don't put up solutions to ongoing challenges. It against the CONTRIBUTING guidelines and CODE_OF_CONDUCT as well as against online competitions guidelines.
