### ISSUE TITLE
Linear Search in array

### ISSUE THREAD

**Issue by PrashantSrivastava33** [SarthakKeshari/CPP-Questions-and-Solutions#29]
### Enter your question - 
Write a program to perform a linear search in an integer array.

### Enter link to the question(if question belongs to any online platform) - 
no link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
array, integer, search

**Comment by PrashantSrivastava33** [comment]
@SarthakKeshari , please assign me this question.

**Comment by SarthakKeshari** [comment]
@PrashantSrivastava33,
Kindly add your solution to "Searching" folder
Deadline - 28/09/2021
