### ISSUE TITLE
Find All Duplicates in an Array

### ISSUE THREAD

**Issue by Ritwik009** [SarthakKeshari/CPP-Questions-and-Solutions#310]
### Enter your question - 
Given an integer array nums of length n where all the integers of nums are in the range [1, n] and each integer appears once or twice, return an array of all the integers that appears twice.

You must write an algorithm that runs in O(n) time and uses only constant extra space.

 

Example 1:

Input: nums = [4,3,2,7,8,2,3,1]
Output: [2,3]
Example 2:

Input: nums = [1,1,2]
Output: [1]
Example 3:

Input: nums = [1]
Output: []
 

Constraints:

n == nums.length
1 <= n <= 105
1 <= nums[i] <= n
Each element in nums appears once or twice.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/find-all-duplicates-in-an-array/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Hash Tables

**Comment by SarthakKeshari** [comment]
@Ritwik009,
Kindly add your solution to "leetcode" folder.
Deadline - 07/10/2021
