### ISSUE TITLE
Letter A

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/CPP-Questions-and-Solutions#324]
### Enter your question - 
Write a program to print letter A exactly as shown below -

![image](https://user-images.githubusercontent.com/55992140/136321605-a4872c69-0abb-4f14-8194-cbdc76444cce.png)

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
loops, pattern printing

**Comment by ilimugur** [comment]
Kindly assign this issue to me.
