### ISSUE TITLE
Letter C

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/CPP-Questions-and-Solutions#326]
### Enter your question - 
Write a program to print letter C exactly as shown below -

![image](https://user-images.githubusercontent.com/55992140/136354454-ea50a749-83ca-46e7-858f-fe485c31b31d.png)

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
loops, pattern printing

**Comment by ilimugur** [comment]
Kindly assign this issue to me.
