### ISSUE TITLE
Letter H

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/CPP-Questions-and-Solutions#329]
### Enter your question - 
Write a program to print letter H exactly as shown below -

![image](https://user-images.githubusercontent.com/55992140/136355084-2103b129-9cad-427a-b983-333b0d8b3575.png)

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
loops, pattern printing

**Comment by absolute-looser** [comment]
can I do this

**Comment by SarthakKeshari** [comment]
@absolute-looser,
Kindly add your solution to "Pattern Printing" folder.
Deadline - 08/10/2021
