### ISSUE TITLE
👋 For new Contributors

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/CPP-Questions-and-Solutions#33]
### Discussed in https://github.com/SarthakKeshari/CPP-Questions-and-Solutions/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **SarthakKeshari** September 26, 2021</sup>
Hello Contributors,
Some issues have been tagged as good first issue. You may ask for assigning those issue to you if you're beginner to open source contribution. If there is no such issue open for you mention your name below in the comment section.</div>

**Comment by Rajat-Jain29** [comment]
@SarthakKeshari Is there any other good first issue?

**Comment by SarthakKeshari** [comment]
Hello @Rajat-Jain29,
You may create an issue that you wish to solve and I will tag it for you as good first issue.
And if you want me to create one for you let me know here

**Comment by Rajat-Jain29** [comment]
Okay @SarthakKeshari I will create pull request by myself you can merge under Hacktoberfest label.
