### ISSUE TITLE
Letter J

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/CPP-Questions-and-Solutions#331]
### Enter your question - 
Write a program to print letter J exactly as shown below -

![image](https://user-images.githubusercontent.com/55992140/136355404-962fd793-27b7-4565-992b-ecf48cf4d5b9.png)

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
loops, pattern printing

**Comment by AditiRai17** [comment]
Kindly assign me this issue.

**Comment by AditiRai17** [comment]
![Screenshot (753)](https://user-images.githubusercontent.com/91966396/136712014-6c663a2f-f86a-49ab-942d-36dfef099566.png)
![Screenshot (752)](https://user-images.githubusercontent.com/91966396/136712028-5ee8f491-997a-449f-b8ba-e4b0910c5e48.png)
