### ISSUE TITLE
Letter L

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/CPP-Questions-and-Solutions#333]
### Enter your question - 
Write a program to print letter L exactly as shown below -

![image](https://user-images.githubusercontent.com/55992140/136356007-69cc2730-41d5-4a51-92fd-fcbfb35e6cf5.png)

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
loops, pattern printing

**Comment by SarthakKeshari** [comment]
@Ritwik009,
Kindly add your solution to "Pattern Printing" folder
Deadline - 10/10/2021

**Comment by Anova07** [comment]
@SarthakKeshari 
Please review
Letter L and Letter N #502

I have made one PR for both the Pattern Printing questions

Please let me know if any changes are to be  made.
