### ISSUE TITLE
Letter N

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/CPP-Questions-and-Solutions#335]
### Enter your question - 
Write a program to print letter N exactly as shown below -

![image](https://user-images.githubusercontent.com/55992140/136356488-5ba26ef5-d49b-453b-ba8b-39ecf83e4d9a.png)

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
loops, pattern printing

**Comment by mdArshad10** [comment]
please assign it to me

**Comment by SarthakKeshari** [comment]
@mdArshad10,
Kindly add your solution to "Pattern Printing" folder.
Deadline - 12/10/2021

**Comment by SarthakKeshari** [comment]
@Anova07,
Kindly add your solution to "Pattern Printing" folder
Deadline - 18/10/2021

**Comment by Anova07** [comment]
@SarthakKeshari 
Please review
Letter L and Letter N #502

I have made one PR for both the Pattern Printing questions

Please let me know if any changes are to be  made.
