### ISSUE TITLE
Movie Weekend 

### ISSUE THREAD

**Issue by Vedika-Agrawal** [SarthakKeshari/CPP-Questions-and-Solutions#34]
Question - 
Little Egor is a huge movie fan. He likes watching different kinds of movies: from drama movies to comedy movies, from teen movies to horror movies. He is planning to visit cinema this weekend, but he's not sure which movie he should watch.

There are n movies to watch during this weekend. Each movie can be characterized by two integers Li and Ri, denoting the length and the rating of the corresponding movie. Egor wants to watch exactly one movie with the maximal value of Li × Ri. If there are several such movies, he would pick a one with the maximal Ri among them. If there is still a tie, he would pick the one with the minimal index among them.

Your task is to help Egor to pick a movie to watch during this weekend.

Input
The first line of the input contains an integer T denoting the number of test cases.

The first line of the test case description contains an integer n.

The second line of the test case description contains n integers L1, L2, ...,Ln. The following line contains n integers R1, R2, ..., Rn.

Output
For each test case, output a single integer i denoting the index of the movie that Egor should watch during this weekend. Note that we follow 1-based indexing.

Constraints
1 ≤ T ≤ 5
1 ≤ n ≤ 100
1 ≤ Li, Ri ≤ 100
Sample Input 1 
2
2
1 2
2 1
4
2 1 4 1
2 4 1 4
Sample Output 1 
1
2

### Enter link to the question(if question belongs to any online platform) - 
https://www.codechef.com/problems/MOVIEWKN

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array

**Comment by Vedika-Agrawal** [comment]
I would like to work on this issue please assign this issue to me.

**Comment by SCHW18TZ** [comment]
I want to work in this issue can you assign it to me?

**Comment by SarthakKeshari** [comment]
@Vedika-Agrawal,
Kindly add your solution to "Codechef" Folder.
Deadline - 30/09/2021
