### ISSUE TITLE
Letter X

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/CPP-Questions-and-Solutions#340]
### Enter your question - 
Write a program to print letter X exactly as shown below -

![image](https://user-images.githubusercontent.com/55992140/136357743-23224fba-8082-4b5e-a5fe-a2cf7feaf909.png)

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
loops, pattern printing

**Comment by SarthakKeshari** [comment]
@cyberskull99297,
Go ahead, Kindly add your solution to "Pattern Printing" folder.
Deadline - 10/10/2021

**Comment by cyberskull99297** [comment]
Being a beginner, I do not have much knowledge of open source. Kindly review, if my contribution was correct or there is something  I need to improve.
Thanks

**Comment by SarthakKeshari** [comment]
@cyberskull99297,
It seems you have merged it into your own repository.
Give me time till 2:30 AM today.
I will add the detailed steps to make a successfull pull request.

Will that be fine?

**Comment by cyberskull99297** [comment]
@SarthakKeshari  Yes!, Thank You. That will be very helping to me.

**Comment by SarthakKeshari** [comment]
@cyberskull99297,
Its showing some conflicts.

Close all the PRs(pull requests) and remove the folder on you local system and Delete the copy of this repository from your GitHub then, 

Follow these steps - 

Kindly go through the below steps to make your first successful contribution - 
Steps to contribute - 
1) Sign into your GitHub account, or create a GitHub account
2) Fork the project repository by clicking the Fork button
3) git clone URL_OF_FORK
4)  navigate to it the repository created on local machine by the execution of Step 3 using: cd NAME_OF_REPOSITORY
5) git remote add upstream URL_OF_ORIGINAL_PROJECT
6) git pull upstream main
7) Create new branch: git checkout -b BRANCH_NAME
8) Make changes in your local system repository
9) git add -A
10) git commit -m "DESCRIPTION OF CHANGES(4 to 5 words)"
11) git push origin BRANCH_NAME
12) Go to your Github repo now and Click on "Compare and pull request"
13) Fill PR template(in case admin has provided it) and click on "Create Pull request"
14) Once your Pull Request(most people call it PR) is merged then delete the branch you have created on Step 7
15) For deleting branch:
a) git checkout main
b) git branch -D BRANCH_NAME
16) git pull upstream main
