### ISSUE TITLE
Next Greater Element (using Stack)

### ISSUE THREAD

**Issue by Master-Helix** [SarthakKeshari/CPP-Questions-and-Solutions#346]
### Enter your question -  
Given an array arr[ ] of size N having distinct elements, the task is to find the next greater element for each element of the array in order of their appearance in the array.
Next greater element of an element in the array is the nearest element on the right which is greater than the current element.
If there does not exist next greater of current element, then next greater element for current element is -1. For example, next greater of the last element is always -1.

### Enter link to the question(if question belongs to any online platform) - 
https://practice.geeksforgeeks.org/problems/next-larger-element-1587115620/1

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Stack

**Comment by SarthakKeshari** [comment]
@Master-Helix,
Kindly add your solution to "GeeksForGeeks" folder.
Deadline - 08/10/2021
