### ISSUE TITLE
Semi sort 1

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/CPP-Questions-and-Solutions#36]
### Enter your question - 
Write a program to sort half of the array in ascending and second half in descending or vice versa depending on users choice.
AD - Ascending then descending
DA - Descending then ascending

Sample test case - 
Input - 
Enter sorting style: AD
Enter number of elements in the array: 5
Numbers: 1 4 2 4 2

Output - 
Semi-sorted: 1 2 4 4 2

Explaination - 
Array -> 1 4 2 4 2
Part-one -> 1 4 2 -> (Sorting part-one in ascending order since user enter AD) -> 1 2 4
Part-two -> 4 2 -> (Sorting part-two in descending order since user enter AD) -> 4 2
Therefore, output -> 1 2 4 4 2

### Enter link to the question(if question belongs to any online platform) - 
No Link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, sorting

**Comment by aaditya9899** [comment]
please assign it to me

**Comment by aaditya9899** [comment]
hey can you assign it to me?

**Comment by SarthakKeshari** [comment]
@aaditya9899,
Kindly add your solution to "Sorting" folder.
Deadline - 1/10/2021

**Comment by aaditya9899** [comment]
its showing permission denied when i am pushing my code

**Comment by SarthakKeshari** [comment]
git clone command and git remote add upstream  will have different urls. Your must have clone the original project that's why it gives such error

**Comment by aaditya9899** [comment]
okay so how to fix this?

**Comment by SarthakKeshari** [comment]
Remove local system copy of the repo now
and start your steps from git clone and further.
