### ISSUE TITLE
Reverse a linked list in Cpp using recursion 

### ISSUE THREAD

**Issue by KAUSHIK-DEKA** [SarthakKeshari/CPP-Questions-and-Solutions#374]
### Enter your question - 
Reverse a linked list using recursion in c

### Enter link to the question(if question belongs to any online platform) - 
https://www.geeksforgeeks.org/recursively-reversing-a-linked-list-a-simple-implementation/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Your answer
Linked list. Data Structure.

**Comment by SarthakKeshari** [comment]
@KAUSHIK-DEKA,
Since its a C++ repo. C solutions won't get accepted.

**Comment by SarthakKeshari** [comment]
@KAUSHIK-DEKA,
Kindly let me know if there are any queries or shall I close this issue?

**Comment by KAUSHIK-DEKA** [comment]
> @KAUSHIK-DEKA, Since its a C++ repo. C solutions won't get accepted.

I have change the code to cpp.  I have created the pull request. You can have a look.

**Comment by SarthakKeshari** [comment]
@KAUSHIK-DEKA,
Kindly wait for the issue to assigned before creating the PR as per the repo guidelines
