### ISSUE TITLE
Maximum length of Bitonic Sequence

### ISSUE THREAD

**Issue by PrakharRathore123** [SarthakKeshari/CPP-Questions-and-Solutions#381]
### Enter your question - 
Given an array A containing n positive integers, a subarray A[i … j] is bitonic if there is a k with i <= k <= j such that A[i] <= A[i + 1] … = A[k + 1] >= .. A[j – 1] > = A[j].  Calculate the length of the maximum length bitonic subarray. A sequence, sorted in increasing order is considered Bitonic with the decreasing part as empty. Similarly, decreasing order sequence is considered Bitonic with the increasing part as empty. 

### Enter link to the question(if question belongs to any online platform) - 
-

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array , Recursion , Dynamic Programming

**Comment by PrakharRathore123** [comment]
@SarthakKeshari Kindly issue me this problem

**Comment by SarthakKeshari** [comment]
@PrakharRathore123,
Kindly provide a test case and explaination

**Comment by SarthakKeshari** [comment]
@PrakharRathore123,
Kindly add your solution to "Dynamic Programming" folder.
Deadline - 09/10/2021
