### ISSUE TITLE
Egg dropping Problem

### ISSUE THREAD

**Issue by PrakharRathore123** [SarthakKeshari/CPP-Questions-and-Solutions#382]
### Enter your question - 
Given a certain amount of floors  and also given certain amount of eggs .What is the least amount of egg drops one has to perform to find out the threshold floor. Threshold floor is one from which the egg starts breaking and also egg breaks for all the floors above. Also, if egg dropped from any floor below the threshold floor, it won’t break.
Test Cases:
An egg that survives a fall can be used again.
A broken egg must be discarded.
The effect of a fall is the same for all eggs.
If an egg breaks when dropped, then it would break if dropped from a higher floor.
If an egg survives a fall then it would survive a shorter fall.

### Enter link to the question(if question belongs to any online platform) - 
-
### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Recursion , Array , Dynamic programming

**Comment by PrakharRathore123** [comment]
@SarthakKeshari Kindly check

**Comment by SarthakKeshari** [comment]
@PrakharRathore123,
Kindly enter 2 test cases with proper output explaination
