### ISSUE TITLE
Longest Palindromic Subsequence

### ISSUE THREAD

**Issue by PrakharRathore123** [SarthakKeshari/CPP-Questions-and-Solutions#387]
### Enter your question - 
Given a sequence, find the length of the longest palindromic subsequence in it.

### Test Cases-
Test 1 ) For the input of string="PRAKHAR"
Longest Palindromic Subsequence possible is "RAHAR"
so max length is 5

Test 2 ) For the input of string="SARTHAK"
Longest Palindromic Subsequence possible is "AHA"
so max length is 3
 
### Enter link to the question(if question belongs to any online platform) - 
-

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Recursion , Dynamic programming , Array ,String.

**Comment by PrakharRathore123** [comment]
@SarthakKeshari Kindly issue me this problem

**Comment by SarthakKeshari** [comment]
@PrakharRathore123,
Kindly add your solution to "Dynamic Programming" folder.
Deadline - 10/10/2021

**Comment by SarthakKeshari** [comment]
@PrakharRathore123,
Perfect
