### ISSUE TITLE
Sorting an array

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/CPP-Questions-and-Solutions#4]
### Enter your question - 
Take 10 numbers as input from the user and sort it

### Enter link to the question(if question belongs to any online platform) - 
NO link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
sorting, array

### Question belongs to which section/subsection(eg - Arrays/1D Arrays) - 
Arrays/1D Arrays

**Comment by BodaleDenis** [comment]
I want to contribute to this, cam I be assigned ?
Thank you!

**Comment by SarthakKeshari** [comment]
@BodaleDenis,
Kindly add your solution to "Basic Codes" folder.
Deadline - 30/09/2021
