### ISSUE TITLE
Greedy Algorithms

### ISSUE THREAD

**Issue by 17rashi** [SarthakKeshari/CPP-Questions-and-Solutions#405]

**Comment by 17rashi** [comment]
@SarthakKeshari Sir, can I put questions along with the solution on this topic?

**Comment by 17rashi** [comment]
Thank you Sir, I have completed the work, please check and let me know if any kind of change is required.

**Comment by SarthakKeshari** [comment]
@17rashi,
I will accept it, but for further issues, kindly fill the proper "add a question" template

**Comment by 17rashi** [comment]
Okay Sir, Thanks a lot. I am a beginner to open source. Really Thankful for your cooperation and guidance.
