### ISSUE TITLE
For Loop

### ISSUE THREAD

**Issue by Harshit-Poddar90** [SarthakKeshari/CPP-Questions-and-Solutions#411]
### Enter your question - 
A for loop is a programming language statement which allows code to be repeatedly executed.

The syntax is

for ( <expression_1> ; <expression_2> ; <expression_3> )
    <statement>
expression_1 is used for initializing variables which are generally used for controlling the terminating flag for the loop.
expression_2 is used to check for the terminating condition. If this evaluates to false, then the loop is terminated.
expression_3 is generally used to update the flags/variables.

### Enter link to the question(if question belongs to any online platform) - 
https://www.hackerrank.com/challenges/c-tutorial-for-loop/problem

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
loops.

**Comment by SarthakKeshari** [comment]
@Harshit-Poddar90,
Kindly add your solution to "Hackerrank" folder.
Deadline - 12/10/2021
