### ISSUE TITLE
Odd after even LinkedList

### ISSUE THREAD

**Issue by anshuman725** [SarthakKeshari/CPP-Questions-and-Solutions#413]
### Enter your question - 
For a given singly linked list of integers, arrange the elements such that all the even numbers are placed after the odd numbers. The relative order of the odd and even terms should remain unchanged.

### Test Cases-
Sample Input 1 :
1
1 4 5 2 -1

Sample Output 1 :
1 5 4 2 

Sample Input 2 :
2
1 11 3 6 8 0 9 -1
10 20 30 40 -1

Sample Output 2 :
1 11 3 9 6 8 0
10 20 30 40

### Enter link to the question(if question belongs to any online platform) - 
[Link to Question](https://www.geeksforgeeks.org/rearrange-a-linked-list-such-that-all-even-and-odd-positioned-nodes-are-together)

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
LinkedList

**Comment by anshuman725** [comment]
> @anshuman725,
> May I know, is this question from GeeksForGeeks?

@SarthakKeshari  it's from the course of Coding Ninja's, But we can find this question on GeeksForGeeks as Well.

**Comment by anshuman725** [comment]
@SarthakKeshari Done!

**Comment by diwakar1998** [comment]
can multiple people solve same issue?
