### ISSUE TITLE
Digit Names

### ISSUE THREAD

**Issue by KodeInt** [SarthakKeshari/CPP-Questions-and-Solutions#42]
### Enter your question - 
Write a program to display digit name

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Basic, If else

**Comment by KodeInt** [comment]
@SarthakKeshari Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
@KodeInt,
Kindly place your solution in "Basic codes" folder.
Deadline - 29/09/2021
