### ISSUE TITLE
Installing IDE - Steps to install Dev C++

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/CPP-Questions-and-Solutions#434]
### Enter topic you want to work upon(eg- String, Loop) -
Installing IDE

### Enter sub-topic you want to work upon(eg- for loop, pow())
Steps to install Dev C++

### ***Answer this question when you claim the issue***

<br><br>

Templates for reference - [.txt](https://github.com/SarthakKeshari/CPP-Questions-and-Solutions/blob/main/Documentation/Template_TXT_Reference.md) and [.html](https://github.com/SarthakKeshari/CPP-Questions-and-Solutions/blob/main/Documentation/Template_HTML_Reference.html)
#### For contributors opting for .txt are requested to visit .html too in order to get clear idea what content to write and how it will be diplayed on the webpage.

<br>

By creating/claiming the issue or by creating PR(pull request) for this issue you agree to the below conditions -

- [x] I affirm that my document is less than **20%** plagarised. <br>
- [x] If my document is found to be more than **20%** plagarised, my PR(pull request) can be rejected without any prior information. <br>
- [x] I give the right to maintainers/admins/collaborators of this repository/project/website to amend/add/remove my document wherever/whenever is found necessary. <br>

**Comment by aaditya9899** [comment]
hey please assign it to me

**Comment by SarthakKeshari** [comment]
@absolute-looser,
Kindly note

1. Follow the reference template -
 Templates for reference - [.txt](https://github.com/SarthakKeshari/CPP-Questions-and-Solutions/blob/main/Documentation/Template_TXT_Reference.md) and [.html](https://github.com/SarthakKeshari/CPP-Questions-and-Solutions/blob/main/Documentation/Template_HTML_Reference.html)
2. Proper screenshots are needed(for the points/steps mentioned wherever its found necessary).
3. Make a folder and with the name "Topic-Subtopic" and place all your .png and .txt/.html file there.
4. Add your folder to "Documentation" folder.

Deadline - 20/10/2021
