### ISSUE TITLE
Subarray with given sum

### ISSUE THREAD

**Issue by rajraii** [SarthakKeshari/CPP-Questions-and-Solutions#437]
### Enter your question - 
Given an array of positive and negative numbers. Find if there is a subarray (of size at-least one) with 0 sum.

### Enter link to the question(if question belongs to any online platform) - 
https://practice.geeksforgeeks.org/problems/subarray-with-0-sum-1587115621/1

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array

**Comment by Himanshi1207** [comment]
can you assign this to me?

**Comment by rajraii** [comment]
@SarthakKeshari hey man, if I raised the issue first shouldn't you assign this to me? 
Isnt it partiality?
