### ISSUE TITLE
GCD using Recursion

### ISSUE THREAD

**Issue by PrasoonJain2002** [SarthakKeshari/CPP-Questions-and-Solutions#46]
### Enter your question - 
Find the GCD of two numbers by using Recursive Technique.

### Enter link to the question(if question belongs to any online platform) - 
No Link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Recursion

**Comment by PrasoonJain2002** [comment]
I have submitted a PR please review it.

**Comment by PrasoonJain2002** [comment]
@SarthakKeshari Kindly assign me this algorithm.

**Comment by SarthakKeshari** [comment]
@PrasoonJain2002,
Kindly add your solution to "Recursion" folder.
Deadline - 30/09/2021
