### ISSUE TITLE
Substring Concatenation - Interviewbit

### ISSUE THREAD

**Issue by sarthakvijay** [SarthakKeshari/CPP-Questions-and-Solutions#468]
### Enter your question - 
Substring Concatenation - Interviewbit

### Enter link to the question(if question belongs to any online platform) - 
https://www.interviewbit.com/problems/substring-concatenation/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Dynamic programming - String

**Comment by SarthakKeshari** [comment]
@sarthakvijay,
Kindly create a folder "Interviewbit" and add your solution in it.
Deadline - 14/10/2021
