### ISSUE TITLE
Max. Subarray sum

### ISSUE THREAD

**Issue by PrakharRathore123** [SarthakKeshari/CPP-Questions-and-Solutions#47]
### Enter your question - 
Find the contiguous sub-array which has the maximum sum.

### Enter link to the question(if question belongs to any online platform) - 
NO LINK

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, loop.

**Comment by PrakharRathore123** [comment]
@SarthakKeshari Kindly assign me this algorithm.

**Comment by SarthakKeshari** [comment]
@PrakharRathore123,
Go ahead, Kindly place this question in "Arrays/1D Arrays" folder
Deadline - 30/09/2021
