### ISSUE TITLE
Letter Combinations of a Phone Number

### ISSUE THREAD

**Issue by ThejaswinS** [SarthakKeshari/CPP-Questions-and-Solutions#479]
### Enter your question - 
Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. Return the answer in any order.

A mapping of digit to letters (just like on the telephone buttons) is given below. Note that 1 does not map to any letters.

 

Example 1:

Input: digits = "23"
Output: ["ad","ae","af","bd","be","bf","cd","ce","cf"]
Example 2:

Input: digits = ""
Output: []
Example 3:

Input: digits = "2"
Output: ["a","b","c"]
 

Constraints:

0 <= digits.length <= 4
digits[i] is a digit in the range ['2', '9'].

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/letter-combinations-of-a-phone-number/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
string, medium

**Comment by aaditya9899** [comment]
hey can you assign me this under hacktoberfest label?

**Comment by SarthakKeshari** [comment]
@ThejaswinS,
Kindly add your solution to "leetcode" folder.
Deadline - 18/10/2021
