### ISSUE TITLE
Balancing parenthesis

### ISSUE THREAD

**Issue by mack611** [SarthakKeshari/CPP-Questions-and-Solutions#48]
### Enter your question - 
CHECK FOR BALANCED PARENTHESIS USING STACK (WITHOUT USING STL)

### Enter link to the question(if question belongs to any online platform) - 
no

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
stacks,arrays,fuctions

**Comment by mack611** [comment]
@SarthakKeshari pls assign my issue

**Comment by SarthakKeshari** [comment]
@mack611,
Kindly add your solution to "Data Structure/Stack" folder.
Deadline - 30/09/2021
