### ISSUE TITLE
Delete Duplicate Folders in System

### ISSUE THREAD

**Issue by Rajat-Jain29** [SarthakKeshari/CPP-Questions-and-Solutions#482]
### Enter your question - 
Two folders (not necessarily on the same level) are identical if they contain the same non-empty set of identical subfolders and underlying subfolder structure. The folders do not need to be at the root level to be identical. If two or more folders are identical, then mark the folders as well as all their subfolders.

Once all the identical folders and their subfolders have been marked, the file system will delete all of them. The file system only runs the deletion once, so any folders that become identical after the initial deletion are not deleted.

Return the 2D array ans containing the paths of the remaining folders after deleting all the marked folders. The paths may be returned in any order.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/delete-duplicate-folders-in-system/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
2D Array

**Comment by SarthakKeshari** [comment]
@Rajat-Jain29,
Kindly add your solution to "leetcode" folder.
Deadline - 18/10/2021
