### ISSUE TITLE
Reverse Integer

### ISSUE THREAD

**Issue by itsooof** [SarthakKeshari/CPP-Questions-and-Solutions#490]
### Enter your question - 
Given a signed 32-bit integer x, return x with its digits reversed. If reversing x causes the value to go outside the signed 32-bit integer range [-2^31, 2^31 - 1], then return 0.

Assume the environment does not allow you to store 64-bit integers (signed or unsigned).

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/reverse-integer/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Math, Medium

**Comment by itsooof** [comment]
Please assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@itsooof,
I hope you have gone through the repo and have checked the issues haven't been already addressed.
If above condition holds.
Kindly add your solution to "leetcode" folder.
Deadline - 18/10/2021
