### ISSUE TITLE
ZigZag Conversion

### ISSUE THREAD

**Issue by itsooof** [SarthakKeshari/CPP-Questions-and-Solutions#492]
### Enter your question - 
The string "PAYPALISHIRING" is written in a zigzag pattern on a given number of rows like this: (you may want to display this pattern in a fixed font for better legibility)

P      A     H    N
A  P  L  S  I  I  G
Y       I      R
And then read line by line: "PAHNAPLSIIGYIR"

Write the code that will take a string and make this conversion given a number of rows:

string convert(string s, int numRows);

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/zigzag-conversion/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
String

**Comment by SarthakKeshari** [comment]
@itsooof,
Kindly add your solution to "leetcode" folder.
Deadline - 18/10/2021
