### ISSUE TITLE
String Datatype 

### ISSUE THREAD

**Issue by anushka-srivastava22** [SarthakKeshari/CPP-Questions-and-Solutions#497]
### A brief about your proposal -
Documentation on string Datatype with a format .txt file
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
@anushka-srivastava22,
Kindly note

1. Follow the reference template -
 Templates for reference - [.txt](https://github.com/SarthakKeshari/CPP-Questions-and-Solutions/blob/main/Documentation/Template_TXT_Reference.md) and [.html](https://github.com/SarthakKeshari/CPP-Questions-and-Solutions/blob/main/Documentation/Template_HTML_Reference.html)
2. Proper screenshots are needed(for the points/steps mentioned wherever its found necessary).
3. Make a folder and with the name "Topic-Subtopic" and place all your .png and .txt/.html file there.
4. Add your folder to "Documentation" folder.

Deadline - 20/10/2021
