### ISSUE TITLE
Birthday Cake Candles

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/CPP-Questions-and-Solutions#5]
### Enter your question - 
You are in charge of the cake for a child's birthday. You have decided the cake will have one candle for each year of their total age. They will only be able to blow out the tallest of the candles. Count how many candles are tallest.

### Enter link to the question(if question belongs to any online platform) - 
https://www.hackerrank.com/challenges/birthday-cake-candles/problem

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Basic, array

### Question belongs to which section/subsection(eg - Arrays/1D Arrays) -
Hackerrank

**Comment by Phaneendra-Bottu** [comment]
I would like to solve this. please assign me to this issue

**Comment by PrashantSrivastava33** [comment]
please assign this question to me

**Comment by SarthakKeshari** [comment]
@Phaneendra-Bottu,
Kindly add your solution to "Hackerrank" folder.
Deadline - 30/09/2021

hacktoberfest tag will be applicable from 1st October
