### ISSUE TITLE
Special Number

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/CPP-Questions-and-Solutions#51]
### Enter your question - 
Write a program to check if a number is Special or not

Explaination - 
A number is said to be special if the sum of the factorial of its digits is equal to the original number.(Make program modular by creating user-defined functions. eg- factorial(), sum())

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Number theory, functions, maths

**Comment by PrasoonJain2002** [comment]
@SarthakKeshari I want to do this please assign it to me.

**Comment by SarthakKeshari** [comment]
@PrasoonJain2002,
Kindly create a folder "Number Theory" and place your solution in it.
Deadline - 01/10/2021
