### ISSUE TITLE
Trapping Rain Water

### ISSUE THREAD

**Issue by YashGosaliya** [SarthakKeshari/CPP-Questions-and-Solutions#521]
### Enter your question - 

Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/trapping-rain-water/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Dynamic Programming, Array

**Comment by YashGosaliya** [comment]
@SarthakKeshari please assign this issue

**Comment by SarthakKeshari** [comment]
@YashGosaliya,
Go ahead, add your solution to "leetcode" folder.
Deadline - 21/10/2021
