### ISSUE TITLE
Setup for Sublime text 

### ISSUE THREAD

**Issue by absolute-looser** [SarthakKeshari/CPP-Questions-and-Solutions#523]
### A brief about your proposal - 
As we can see more and more people in India are in the field of competitive programming and also **Linux** is also getting popular day by day so I propose, the setup of Sublime text in Linux for **competitive programming** as well as normal programming for interview preparation in **C/C++**.

**Comment by absolute-looser** [comment]
@SarthakKeshari  please assign this to me

**Comment by SarthakKeshari** [comment]
@absolute-looser,
Kindly note

1. Follow the reference template -
 Templates for reference - [.txt](https://github.com/SarthakKeshari/CPP-Questions-and-Solutions/blob/main/Documentation/Template_TXT_Reference.md) and [.html](https://github.com/SarthakKeshari/CPP-Questions-and-Solutions/blob/main/Documentation/Template_HTML_Reference.html)
2. Proper screenshots are needed(for the points/steps mentioned wherever its found necessary).
3. Make a folder and with the name "Topic-Subtopic" and place all your .png and .txt/.html file there.
4. Add your folder to "Documentation" folder.

Deadline - 24/10/2021

**Comment by absolute-looser** [comment]
Yeah! it is a documentation but later on i want to work on few important **tree data structures** as i can't see any data structures regarding ### tree.
