### ISSUE TITLE
Shuffling Parities

### ISSUE THREAD

**Issue by PrasoonJain2002** [SarthakKeshari/CPP-Questions-and-Solutions#53]
### Enter your question - 
Chef is given an array A consisting of N positive integers. Chef shuffles the array A and creates a new array B of length N, where Bi=(Ai+i)mod2, for each i(1≤i≤N).

Find the maximum possible sum of integers of the array B, if Chef shuffles the array A optimally.

### Enter link to the question(if question belongs to any online platform) - 
https://www.codechef.com/SEPT21B/problems/SHUFFLIN/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Math, Observation

**Comment by PrasoonJain2002** [comment]
@SarthakKeshari Kindly assign my issue to me.

**Comment by SarthakKeshari** [comment]
@PrasoonJain2002,
Kindly place your solution in "CodeChef" folder.
Deadline - 01/10/2021

**Comment by PrasoonJain2002** [comment]
@SarthakKeshari If I add pull request tomorrow will it be applicable for Hacktoberfest?

**Comment by SarthakKeshari** [comment]
Ok you wish to do so?
