### ISSUE TITLE
Xs and Os

### ISSUE THREAD

**Issue by PrasoonJain2002** [SarthakKeshari/CPP-Questions-and-Solutions#54]
### Enter your question - 
You're playing a game against an opponent on a grid of cells with N rows and N columns. All of the cells are initially empty, and both players normally take turns placing symbols in empty cells (with one player placing Xs and the other placing Os) until a row and/or column becomes entirely filled with one player's symbols (at which point the game ends with that player winning) or all of the cells have been filled without either player winning (in which case the game ends in a draw). Note that a player filling an entire diagonal with their symbols does not cause them to win.
This particular game is in the process of being played, with you placing Xs and your opponent placing Os. The current state of the cell in the i th row from the top and j th column from the left is one of the following:

If Ci,j = ".", the cell is still empty
If Ci,j = "X", an X has been placed in the cell
Otherwise, if Ci,j = "O", an O has been placed in the cell

In the game's current state, both players have made an equal number of turns (in other words, the number of Xs is the same as the number of Os), neither player has won yet, and the game has not yet ended in a draw (meaning that at least one cell is still empty).
Your opponent has just turned their back, giving you the opportunity to immediately place as many additional Xs on the board as you'd like, in any set of empty cells. Determine the minimum number of additional Xs you must place such that placing them would cause you to immediately win (due to a row and/or a column becoming entirely filled with Xs), if this is possible at all. If it is possible, you should also determine the number of different sets of cells in which that minimum number of Xs could be placed. Two sets of cells are considered to be different if either of them includes at least one cell which the other doesn't.

### Enter link to the question(if question belongs to any online platform) - 
https://www.facebook.com/codingcompetitions/hacker-cup/2021/qualification-round/problems/B

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
2D Array

**Comment by PrasoonJain2002** [comment]
@SarthakKeshari Please assign this to me

**Comment by SarthakKeshari** [comment]
@PrasoonJain2002,
Go ahead, Kindly create a new folder "Coding Competitions" save your solution in there.
Deadline - 02/10/2021

Strict reminder - 
Be original in your code. In case of found plagarism in later review even after a successful merge may lead to ban.

**Comment by PrasoonJain2002** [comment]
@SarthakKeshari The code are original written by me.
I myself participated in this contest and qualified for subsequent rounds and these are the code which I have submitted during the contest.
