### ISSUE TITLE
basic pattern

### ISSUE THREAD

**Issue by Phaneendra-Bottu** [SarthakKeshari/CPP-Questions-and-Solutions#56]
### Enter your question - 
print the pattern 
![WhatsApp Image 2021-09-30 at 1 12 09 PM](https://user-images.githubusercontent.com/91441682/135409225-d333b24e-8b4d-48f3-ab07-cf0d58fecd0c.jpeg)

### Enter link to the question(if question belongs to any online platform) - 
NA

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
basic

**Comment by SarthakKeshari** [comment]
@Phaneendra-Bottu,
I hope you'll be using loops?

**Comment by Phaneendra-Bottu** [comment]
yeah. by using for/while/do-while loops

**Comment by SarthakKeshari** [comment]
@Phaneendra-Bottu,
Go ahead, Kindly create a folder "Pattern Printing" and add your solution there.
Deadline - 01/10/2021
