### ISSUE TITLE
Consistency-1

### ISSUE THREAD

**Issue by PrasoonJain2002** [SarthakKeshari/CPP-Questions-and-Solutions#57]
### Enter your question - 
Connie received a string S for her birthday, consisting entirely of uppercase letters (each between "A" and "Z", inclusive).
However, Connie really only likes nice, consistent strings. She considers a string to be consistent if and only if all of its letters are the same.
Each second, Connie may choose one letter in S and replace it with a different letter. If her chosen letter is a vowel, then she may replace it with any consonant of her choice. On the other hand, if her chosen letter is a consonant, then she may replace it with any vowel of her choice. The 5 letters "A", "E", "I", "O", and "U" are considered vowels, while the remaining 21 letters of the alphabet are considered consonants. If a letter appears multiple times in S, she may only replace a single occurrence per second.
Help her determine the minimum number of seconds required to change S into any consistent string. Note that S might already be consistent, in which case 0 seconds would be required.

### Enter link to the question(if question belongs to any online platform) - 
https://www.facebook.com/codingcompetitions/hacker-cup/2021/qualification-round/problems/A1

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
String Analysis

**Comment by PrasoonJain2002** [comment]
@SarthakKeshari  Please assign this to me and also label it for hacktoberfest.

**Comment by PrasoonJain2002** [comment]
@SarthakKeshari Please assign me the question

**Comment by PrasoonJain2002** [comment]
@SarthakKeshari please assign me this question.

**Comment by SarthakKeshari** [comment]
@PrasoonJain2002, Kindly note not more than 2 issues can be assigned at the same time

**Comment by PrasoonJain2002** [comment]
> @PrasoonJain2002, Kindly note not more than 2 issues can be assigned at the same time. Complete the previous one to acquire this.

I have completed please merge it.

**Comment by SarthakKeshari** [comment]
@PrasoonJain2002,
Go ahead, Kindly create a new folder "Coding Competitions" save your solution in there.
Deadline - 02/10/2021
