### ISSUE TITLE
Digit Rotation

### ISSUE THREAD

**Issue by PrashantSrivastava33** [SarthakKeshari/CPP-Questions-and-Solutions#59]
### Enter your question - 
Write a C++ program to get an n-digit number from user and perform the following operation:
input- 659874
operation- 659874->598746->587469->584697->584976->584967
that is, rotate each digit to the left, while keeping 1 extra digit fixed each time.
Also, print the maximum number obtained from these combinations, in this case, max=598746

### Enter link to the question(if question belongs to any online platform) - 
Your answer

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Looping

**Comment by PrashantSrivastava33** [comment]
Please assign me this question

**Comment by SarthakKeshari** [comment]
@PrashantSrivastava33,
Kindly add your solution to "String Handling" folder.
Deadline - 02/10/2021
