### ISSUE TITLE
Prime Game

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/CPP-Questions-and-Solutions#6]
### Enter your question - 
Chef and Divyam are playing a game with the following rules:

First, an integer X! is written on a board.
Chef and Divyam alternate turns; Chef plays first.
In each move, the current player should choose a positive integer D which is divisible by up to Y distinct primes and does not exceed the integer currently written on the board. Note that 1 is not a prime.
D is then subtracted from the integer on the board, i.e. if the integer written on the board before this move was A, it is erased and replaced by A−D.
When one player writes 0 on the board, the game ends and this player wins.
Given X and Y, determine the winner of the game.

### Enter link to the question(if question belongs to any online platform) - 
https://www.codechef.com/problems/PRIGAME

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
functions

### Question belongs to which section/subsection(eg - Arrays/1D Arrays) -
CodeChef

**Comment by NitikaGupta16** [comment]
I would like to solve this. Please assign this issue to me.

**Comment by aaditya9899** [comment]
Please Assign it to me as i have already done it and its working perfectly , i just need to make pull request.
Thankx

**Comment by SarthakKeshari** [comment]
@NitikaGupta16,
Fo ahead, Kindly add your solution to "CodeChef" folder.
Deadline - 1/10/2021

Hacktoberfest tag will be applicable from 1st October
