### ISSUE TITLE
Variable sized arrays - Hackerrank

### ISSUE THREAD

**Issue by Pranavanbu28** [SarthakKeshari/CPP-Questions-and-Solutions#63]
### Enter your question - 
Consider an n-element array, **a**, where each index **i**  in the array contains a reference to an array of **ki** integers (where the value of  **ki** varies from array to array). 
Given a , you must answer q queries. Each query is in the format i j, where **i** denotes an index in array  **a** and  **j** denotes an index in the array located at **a[i]** . For each query, find and print the value of element j in the array at location **a[i]**.

### Enter link to the question(if question belongs to any online platform) - 
https://www.hackerrank.com/challenges/variable-sized-arrays/problem

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array

**Comment by Pranavanbu28** [comment]
Hi @SarthakKeshari , I would like to work on this issue and please add hactoberfest label to this issue, if you may.

**Comment by SarthakKeshari** [comment]
@Pranavanbu28,
Question is too easy to be considered for hacktoberfest.

If you wish to count your contribution towards this repository you may go ahead

**Comment by SarthakKeshari** [comment]
@Pranavanbu28,
Kindly add your solution to "Hackerrank" folder.
Deadline - 02/10/2021

**Comment by Pranavanbu28** [comment]
So this can't be considered as a question for hactoberfest?

**Comment by SarthakKeshari** [comment]
Hard and medium level questions are being taken into consideration
