### ISSUE TITLE
Find the Highest Altitude (LeetCode)

### ISSUE THREAD

**Issue by silicolicious** [SarthakKeshari/CPP-Questions-and-Solutions#64]
### Find the Highest Altitude
There is a biker going on a road trip. The road trip consists of n + 1 points at different altitudes. The biker starts his trip on point 0 with an altitude equal to 0.

You are given an integer array gain of length n where gain[i] is the net gain in altitude between points i​​​​​​ and i + 1 for all (0 <= i < n). Return the highest altitude of a point.

### Tags for the question- 
Array

**Comment by silicolicious** [comment]
@SarthakKeshari 
Hi! I am Mageshkrishna R,
I am a registered participant in Hacktoberfest.
I would like to contribute to your repository, kindly assign this issue to me with the label - hacktoberfest
Thank you!

**Comment by SarthakKeshari** [comment]
@silicolicious,
Question is too easy to be considered for hacktoberfest.

If you wish to count your contribution towards this repository you may go ahead

**Comment by SarthakKeshari** [comment]
@silicolicious,
Kindly add this issue to the "leetcode" folder.
Deadline - 02/10/2021
