### ISSUE TITLE
Convert row and column Matrix to Zeroes.

### ISSUE THREAD

**Issue by PrakharRathore123** [SarthakKeshari/CPP-Questions-and-Solutions#67]
### Enter your question - 
Given an m x n integer matrix matrix, if an element is 0, set its entire row and column to 0's and then print the matrix.

### Enter link to the question(if question belongs to any online platform) - 
-
### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Matrix.

**Comment by PrakharRathore123** [comment]
@SarthakKeshari Kindly issue me this problem.

**Comment by SarthakKeshari** [comment]
@PrakharRathore123,
Kindly add your solution to "Arrays/2D Array" folder.
Deadline - 02/10/2021
