### ISSUE TITLE
Best Time to Buy and Sell Stock by Dynamic Programming

### ISSUE THREAD

**Issue by Rajat-Jain29** [SarthakKeshari/CPP-Questions-and-Solutions#68]
Enter your question -
You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.
Return the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return 0.

Enter link to the question(if question belongs to any online platform) -
LeetCode 
Question Link: https://leetcode.com/problems/best-time-to-buy-and-sell-stock/

Tags for the question(eg - Array, Basic, Stack, etc.) -
Dynamic Programming.

**Comment by Rajat-Jain29** [comment]
@SarthakKeshari Please assign to me this question.

**Comment by SarthakKeshari** [comment]
@Rajat-Jain29,
Kindly fill the above template properly. And also mention from which online platform this has been taken.

**Comment by SarthakKeshari** [comment]
@Rajat-Jain29,
Go ahead, Kindly save your solution to "Leetcode" folder.
Deadline - 02/10/2021

Strict reminder -
Be original in your code. In case of found plagarism in later review even after a successful merge may lead to ban.
