### ISSUE TITLE
Pascal Triangle 

### ISSUE THREAD

**Issue by PrakharRathore123** [SarthakKeshari/CPP-Questions-and-Solutions#69]
### Enter your question - 
(a) Given an integer x print the first x rows of pascal's triangle,.
(B) we have given a integer x we need to print that x row only.
. 

### Enter link to the question(if question belongs to any online platform) - 
-

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Recursion.

**Comment by PrakharRathore123** [comment]
@SarthakKeshari Kindly issue me this problem.

**Comment by SarthakKeshari** [comment]
@PrakharRathore123,
Go ahead, Kindly save your solution in "Recursion" folder
Deadline - 03/10/2021
