### ISSUE TITLE
Count the number of inversion in array using merge sort.

### ISSUE THREAD

**Issue by PrakharRathore123** [SarthakKeshari/CPP-Questions-and-Solutions#70]
### Enter your question - 
Two elements a[i] and a[j] form an inversion if a[i] > a[j] and i < j and we have to calculate the total number of inversion in that array.

### Enter link to the question(if question belongs to any online platform) - 
-

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array , Merge sort , Recursion.

**Comment by PrakharRathore123** [comment]
@SarthakKeshari Kindly issue me this problem.

**Comment by SarthakKeshari** [comment]
@PrakharRathore123,
Kindly note more than 2 issues will not be assigned at a time.

**Comment by anuragdw710** [comment]
@SarthakKeshari Kindly issue me this problem.

**Comment by SarthakKeshari** [comment]
@anuragdw710,
Kindly place your solution in "Arrays/1D Arrays" folder.
Deadline - 02/10/2021
