### ISSUE TITLE
Inplace rotate square matrix by 90 degrees using Transpose.

### ISSUE THREAD

**Issue by PrakharRathore123** [SarthakKeshari/CPP-Questions-and-Solutions#71]
### Enter your question - 
Given a n x n matrix, turn it by 90 degrees in clockwise direction without using any extra space.

### Enter link to the question(if question belongs to any online platform) - 
-

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array , Matrix.

**Comment by aaditya9899** [comment]
hey can i work on this

**Comment by SarthakKeshari** [comment]
@aaditya9899,
Go ahead, Kindly add your solution to "Arrays/2D Arrays" folder.
Deadline - 03/10/2021
