### ISSUE TITLE
Prisoners_escape.cpp

### ISSUE THREAD

**Issue by manognyaa** [SarthakKeshari/CPP-Questions-and-Solutions#72]
### question - 
We want to see is there a path from one end to another end along the width.
We first convert the given data to the graph(possibly it will become disconnected graph). 
Consider the soldiers as the nodes and we will add an edge between two soldiers if there range of view has some intersection part or if they are just joining. Check every possible pair of point(Soldiers). Find distance b/w two i.e If(x1 - x2)^2 + (y1 - y2)^2 <= 200 * 200 (100(from soldier1) + 100(from soldier2)). Then add the edge. 

After this we will use bfs to find this path from one end of the canoyn to other end. If there exist then there is no way to escape else there is a way to escape always. Line 35 to 39 in bfs() what we are doing is we are pushing those soldiers whose y coordinates are atmost 100 unit and there view intersect with the bottom part(As we are starting our path search from bottom to top so we push these  or one can also push from the top and search the path to the bottom). Only thing different is we are returning true (line 51) because we reach at the soldier who is atmost 100 unit far from the w(width line at the top) and this ensure that there is path, else if this is never possible then at last we have return (false).

### Enter link to the question(if question belongs to any online platform) - 
Your answer - https://www.hackerearth.com/practice/algorithms/graphs/depth-first-search/practice-problems/algorithm/prison-break-5/

#Input format:
The first line contains three integers L, W, and N – the length and the width of the canyon, and the number of soldiers, respectively.  Each of the following N lines contains a pair of integers Xi and Yi – the coordinates of i-th soldier in the canyon (0 ≤ Xi ≤ L, 0 ≤ Yi ≤ W).  The coordinates are given in meters, relative to the canyon: the southwestern corner of the canyon has coordinates (0, 0), and the northeastern corner of the canyon has coordinates (L,W), as seen in the picture above. Note that passing the canyon may start at coordinate (0,ys) for any 0 ≤ ys ≤ W and  end at coordinate (L,ye) for any 0 &\le; ye ≤ W. Neither ys nor ye need to be integer.

#Output format:
Output a single integer: 0 if the prisoners can escape, 1 if they cannot.

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Your answer - graphs

pr no. - #73 

please kindly assign me this issue `@SarthakKeshari`  sir. I am very much interested to contribute !!

**Comment by SarthakKeshari** [comment]
@manognyaa,
Go ahead, Kindly save your solution to "Data Structure/Graph/Undirected Graph" folder.
Deadline - 03/10/2021
