### ISSUE TITLE
Knapsack - gfg

### ISSUE THREAD

**Issue by syamala27** [SarthakKeshari/CPP-Questions-and-Solutions#78]
### Enter your question - 
You are given weights and values of N items, put these items in a knapsack of capacity W to get the maximum total value in the knapsack. Note that we have only one quantity for each item.

In other words, given two integer arrays val[0..N-1] and wt[0..N-1] which represent values and weights associated with N items respectively. Also given an integer W which represents knapsack capacity, find out the maximum value subset of val[] such that sum of the weights of this subset is smaller than or equal to W. You cannot break an item, either pick the complete item or don’t pick it (0-1 property).

### Enter link to the question(if question belongs to any online platform) - 
problem link - https://practice.geeksforgeeks.org/problems/0-1-knapsack-problem0945/1

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
level - `medium`

I would like to work on this issue. Pls assign me this issue @SarthakKeshari  sir

**Comment by anuragdw710** [comment]
@SarthakKeshari Please assign me this question.

**Comment by SarthakKeshari** [comment]
@syamala27,
Go ahead, Kindly create a folder "GeeksForGeeks" and save your solution in it.
Deadline - 02/10/2021

**Comment by SarthakKeshari** [comment]
@anuragdw710,
Its First Come First Serve. So, in case the deadline is over you'll be assigned next. Till then you may contribute in accordance with CONTRIBUTING.md
