### ISSUE TITLE
Island Perimeter

### ISSUE THREAD

**Issue by rustzz-27** [SarthakKeshari/CPP-Questions-and-Solutions#79]
### Enter your question - 
You are given row x col grid representing a map where grid[i][j] = 1 represents land and grid[i][j] = 0 represents water.

Grid cells are connected horizontally/vertically (not diagonally). The grid is completely surrounded by water, and there is exactly one island (i.e., one or more connected land cells).

The island doesn't have "lakes", meaning the water inside isn't connected to the water around the island. One cell is a square with side length 1. The grid is rectangular, width and height don't exceed 100. Determine the perimeter of the island.

![image](https://user-images.githubusercontent.com/53906186/135575138-5c87ff7a-4c73-441a-86da-6f1f3f9715ce.png)

### Enter link to the question(if question belongs to any online platform) - Leetcode
https://leetcode.com/problems/island-perimeter/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Vectors

**Comment by rustzz-27** [comment]
Kindly assign me this issue under Hacktoberfest 2021
Thanks

**Comment by SarthakKeshari** [comment]
@rustzz-27,
Go ahead, Kindly add your solution to "leetcode" folder.
Deadline - 02/10/2021

Gentle advice for futher Issues - 
Medium and hard level questions will be given preference for Hacktoberfest tag.

**Comment by rustzz-27** [comment]
> @rustzz-27, Go ahead, Kindly add your solution to "leetcode" folder. Deadline - 02/10/2021
> 
> Gentle advice for futher Issues - Medium and hard level questions will be given preference for Hacktoberfest tag.

Thanks

**Comment by rustzz-27** [comment]
Kindly review my pr
#85
