### ISSUE TITLE
Similar Pairs

### ISSUE THREAD

**Issue by Master-Helix** [SarthakKeshari/CPP-Questions-and-Solutions#82]
**### Enter your question** - 

We call two numbers x and y similar if they have the same parity (the same remainder when divided by 2), or if |x−y|=1. For example, in each of the pairs (2,6), (4,3), (11,7), the numbers are similar to each other, and in the pairs (1,4), (3,12), they are not.

You are given an array a of n (n is even) positive integers. Check if there is such a partition of the array into pairs that each element of the array belongs to exactly one pair and the numbers in each pair are similar to each other.

For example, for the array a=[11,14,16,12], there is a partition into pairs (11,12) and (14,16). The numbers in the first pair are similar because they differ by one, and in the second pair because they are both even.

**Input:**-
The first line contains a single integer t (1≤t≤1000) — the number of test cases. Then t test cases follow.

Each test case consists of two lines.

The first line contains an even positive integer n (2≤n≤50) — length of array a.

The second line contains n positive integers a1,a2,…,an (1≤ai≤100).

**Output:-**
For each test case print:

YES if such a partition exists,
NO otherwise.
The letters in the words, YES and NO can be displayed in any case.

**Example - 
(Input)**
7
4
11 14 16 12
2
1 8
4
1 1 1 1
4
1 2 5 6
2
12 13
6
1 6 3 10 5 8
6
1 12 3 10 5 8

**(Output)**
YES
NO
YES
YES
YES
YES
NO

**### Enter link to the question(Codeforces)** -  https://codeforces.com/contest/1360/problem/C

**### Tags for the question** -  Constructive Algorithms, Greedy, Sortings, Graph Matchings

**Comment by Master-Helix** [comment]
Sir @SarthakKeshari,
Kindly assign this question to me for contribution under Hacktoberfest-2021.
Thank You

**Comment by SarthakKeshari** [comment]
@Master-Helix,
Go ahead, Kindly add your solution to "Codeforces" folder.
Deadline - 03/10/2021
