### ISSUE TITLE
Nastia and Nearly Good Numbers

### ISSUE THREAD

**Issue by Fury-MadMax** [SarthakKeshari/CPP-Questions-and-Solutions#83]
**Enter your question -** 

Nastia has 2 positive integers A and B. She defines that:

The integer is good if it is divisible by A⋅B;
Otherwise, the integer is nearly good, if it is divisible by A.
For example, if A=6 and B=4, the integers 24 and 72 are good, the integers 6, 660 and 12 are nearly good, the integers 16, 7 are neither good nor nearly good.

Find 3 different positive integers x, y, and z such that exactly one of them is good and the other 2 are nearly good, and x+y=z.

**Input**
The first line contains a single integer t (1≤t≤10000) — the number of test cases.
The first line of each test case contains two integers A and B (1≤A≤106, 1≤B≤106) — numbers that Nastia has.

**Output**
For each test case print:

"YES" and 3 different positive integers x, y, and z (1≤x,y,z≤1018) such that exactly one of them is good and the other 2 are nearly good, and x+y=z.
"NO" if no answer exists.
You can print each character of "YES" or "NO" in any case.
If there are multiple answers, print any.

**Example**
**Input**
3
5 3
13 2
7 11

**Output**
YES
10 50 60
YES
169 39 208
YES
28 154 182

**Comment by ADARSH906** [comment]
Sir @SarthakKeshari,
Kindly assign this question to me for contribution under Hacktoberfest-2021.

**Comment by SarthakKeshari** [comment]
@Fury-MadMax,
Kindly add your solution to "Codeforces" folder.
Deadline - 02/10/2021
