### ISSUE TITLE
Array with Odd Sum

### ISSUE THREAD

**Issue by Abhicoder03** [SarthakKeshari/CPP-Questions-and-Solutions#86]
Enter your question - 
You are given an array a consisting of n integers.

In one move, you can choose two indices 1≤i,j≤n such that i≠j and set ai:=aj. You can perform such moves any number of times (possibly, zero). You can choose different indices in different operations. The operation := is the operation of assignment (i.e. you choose i and j and replace ai with aj).

Your task is to say if it is possible to obtain an array with an odd (not divisible by 2) sum of elements.

You have to answer t independent test cases.

Input
The first line of the input contains one integer t (1≤t≤2000) — the number of test cases.

The next 2t lines describe test cases. The first line of the test case contains one integer n (1≤n≤2000) — the number of elements in a. The second line of the test case contains n integers a1,a2,…,an (1≤ai≤2000), where ai is the i-th element of a.

It is guaranteed that the sum of n over all test cases does not exceed 2000 (∑n≤2000).

Output
For each test case, print the answer on it — "YES" (without quotes) if it is possible to obtain the array with an odd sum of elements, and "NO" otherwise.

Example

input

5
2
2 3
4
2 2 8 8
3
3 3 3
4
5 5 5 5
4
1 1 1 1

output

YES
NO
YES
NO
NO

link to the question - https://codeforces.com/problemset/problem/1296/A

Tags for the question-  Math

**Comment by Abhicoder03** [comment]
@SarthakKeshari Could you please assign me this question and also add hactoberfest label.

**Comment by SarthakKeshari** [comment]
@Abhicoder03,
Kindly add your solution to "Codeforces" folder.
Deadline - 02/10/2021

**Comment by Abhicoder03** [comment]
Thanks @SarthakKeshari

**Comment by Abhicoder03** [comment]
@SarthakKeshari Done Sir.

**Comment by Abhicoder03** [comment]
@SarthakKeshari I have done the changes what you have told. Now, Could you please merge it.
