### ISSUE TITLE
3Sum(LeetCode)

### ISSUE THREAD

**Issue by silicolicious** [SarthakKeshari/CPP-Questions-and-Solutions#88]
### Enter your question - 
Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.
Notice that the solution set must not contain duplicate triplets.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/3sum/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Two-Pointers, Sorting

**Comment by silicolicious** [comment]
Hey @SarthakKeshari
Can you please assign this issue to me under the label hacktoberfest :)
Thank you!

**Comment by SarthakKeshari** [comment]
@silicolicious,
Go ahead, Kindly add your solution to "Leetcode" folder.
Deadline - 03/10/2021
