### ISSUE TITLE
Merge two sorted linked lists

### ISSUE THREAD

**Issue by Nithish2032** [SarthakKeshari/CPP-Questions-and-Solutions#90]
### Merge two sorted linked lists into one 
Hi. I am a beginner to open source. I want to add a program that takes two sorted linked lists and merges them into one sorted linked list. Please assign me this under hacktoberfest 2021.

**Comment by SarthakKeshari** [comment]
@Nithish2032,
Kindly follow the original Issue template and go through CONTRIBUTING.md for further details.

**Comment by SarthakKeshari** [comment]
@Nithish2032,
Any further queries or shall I close this issue.
