### ISSUE TITLE
RainWater Trapping Probelm

### ISSUE THREAD

**Issue by Adityagupta1625** [SarthakKeshari/CPP-Questions-and-Solutions#98]
### Question - 
Given an array arr[] of N non-negative integers representing the height of blocks. If width of each block is 1, compute how much water can be trapped between the blocks during the rainy season. 

### Example-
Input:
N = 6
arr[] = {3,0,0,2,0,4}

Output:
10

### Link to Question - 
https://practice.geeksforgeeks.org/problems/trapping-rain-water-1587115621/1

### Tags  - 
<code> Array</code>  <code> Medium</code>   <code> DP</code>

**Comment by Prajakta102** [comment]
Kindly assign this task to me.

**Comment by SarthakKeshari** [comment]
@Prajakta102,
Kindly add your solution to "GeeksForGeeks" folder.
Deadline - 03/10/2021
